Repository GEOLYTIX/xyz, pull requests merged in 2023-11, with the labels that each got.

#989 Allow a Query to Set the Edit Options
  lib/ui/locations/entries/text.mjs
Labels: Feature

#988 sqlfilter / json url parameter encoding
  api/api.js
  lib/ui/elements/dropdown.mjs
  lib/ui/layers/filters.mjs
  lib/ui/utils/tabulatorUtils.mjs
  lib/utils/paramString.mjs
  mod/utils/sqlFilter.js
Labels: Bug

#987 Use ID if field is undefined in theme.
  lib/layer/themes/distributed.mjs
  lib/ui/layers/_layers.mjs
Labels: Bug

#991 Provide format:tiles source and proj param
  lib/layer/format/tiles.mjs
Labels: Bug, Feature

#992 no_result configuration for gazetteer.
  lib/utils/gazetteer.mjs
Labels: Feature

#993 Sync fields; Geometry edit updates; Boolean Fields
  lib/location/decorate.mjs
  lib/ui/locations/entries/boolean.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/locations/entries/pin.mjs
  lib/ui/locations/entries/text.mjs
  lib/ui/locations/entries/textarea.mjs
  public/css/_ui.css
  public/css/ui.css
Labels: Bug, Feature, Code

#995 layer.view() method must return layer
  lib/ui/layers/listview.mjs
  lib/ui/layers/view.mjs
Labels: Feature, Code

#994 Cancel drawing interaction with escape key.
  lib/mapview/interactions/draw.mjs
Labels: Bug, Feature

#998 Get nonlanguage [view] templates
  mod/utils/languageTemplates.js
  mod/view.js
Labels: Bug

#999 Layer should be merged into workspace values
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
  mod/workspace/getTemplate.js
Labels: Bug

#1001 Assign layer as request param for queries
  mod/query.js
  mod/workspace/templates/cluster.js
  mod/workspace/templates/cluster_hex.js
  mod/workspace/templates/get_last_location.js
  mod/workspace/templates/mvt_cache.js
  mod/workspace/templates/wkt.js
Labels: Bug

#1002 get and merge templates in a for of loop
  mod/workspace/getLayer.js
Labels: Bug

#1003 layer param and geom in geojson query
  mod/workspace/templates/geojson.js
Labels: Bug

#1000 Confirm changes on close and edit toggle
  lib/ui/locations/view.mjs
Labels: Feature

#1008 Fix toggling edit mode with no changes
  lib/ui/locations/view.mjs
Labels: Bug

#1004 Use origin request param instead of process.env.ALIAS
  mod/user/_user.js
  mod/user/admin.js
  mod/user/delete.js
  mod/user/login.js
  mod/user/register.js
  mod/user/update.js
  mod/user/verify.js
  mod/utils/mailer.js
  mod/workspace/templates/mails.js
  public/views/_user.html
Labels: Bug, Code

#1006 Layer Restrictions
  lib/ui/layers/view.mjs
  public/css/_icons.css
  public/css/ui.css
Labels: Feature

#1007 renamed color var, added new color var, changed bg color of drawer
  public/css/_button.css
  public/css/_colours.css
  public/css/_drawer.css
  public/css/_inputs.css
  public/css/_layerview.css
  public/css/_locationview.css
  public/css/_tabview.css
  public/css/_ui.css
  public/css/mapp.css
  public/css/ui.css
Labels: Feature

#1009 mvt clear source and refresh
  lib/layer/decorate.mjs
  lib/layer/format/mvt.mjs
Labels: Bug

#1010 Skip themes with skip flag
  lib/layer/decorate.mjs
  lib/ui/layers/panels/style.mjs
Labels: Feature

#1014 strcturedClone template in getLayer
  mod/utils/merge.js
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
Labels: Bug

#1013 remove mvt_cache reference; create mvt query
  api/api.js
  express.js
  lib/layer/Style.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/location/decorate.mjs
  lib/location/get.mjs
  mod/mvt.js
  mod/query.js
  mod/workspace/cache.js
  mod/workspace/templates/_mails.js
  mod/workspace/templates/_msgs.js
  mod/workspace/templates/_queries.js
  mod/workspace/templates/_views.js
  mod/workspace/templates/mvt.js
  mod/workspace/templates/mvt_cache.js
  mod/workspace/templates/mvt_cache_delete_intersects.js
Labels: Feature, Code
