Repository GEOLYTIX/xyz, pull requests merged in 2023-10, with the labels that each got.

#941 Ensure that featurelookup returns nought from style method.
  lib/layer/Style.mjs
  lib/ui/locations/entries/mvt_clone.mjs
Labels: Bug

#937 Assign location style to layer type default style.
  lib/ui/locations/entries/mvt_clone.mjs
  lib/ui/locations/entries/vector_layer.mjs
Labels: Feature

#944 Numeric Entry Module Refactor
  lib/ui/locations/entries/numeric.mjs
Labels: Bug

#942 Edit Mode with Null Geometry
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#947 Enable dataview entry with data from querycheck on update.
  lib/ui/locations/entries/dataview.mjs
Labels: Bug

#948 Fix Source clear bug
  lib/layer/format/mvt.mjs
Labels: Bug

#949 Remove duplication of create button when entry geometry is null
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#952 Flag for suffix_date for cloudinary image upload
  lib/ui/locations/entries/cloudinary.mjs
Labels: Feature

#954 Add reserved asterisk role
  mod/utils/roles.js
Labels: Feature

#956 Drawing elements must enable highlight interaction callback
  lib/ui/elements/drawing.mjs
Labels: Bug

#950 Vector cluster
  lib/layer/_layer.mjs
  lib/layer/fade.mjs
  lib/layer/format/_format.mjs
  lib/layer/format/cluster.mjs
  lib/layer/format/vector.mjs
  lib/mapview/interactions/highlight.mjs
  lib/utils/featureFormats.mjs
  mod/layer/_layer.js
  mod/layer/cluster.js
  mod/query.js
  mod/workspace/assignTemplates.js
  public/js/queries/cluster.js
  public/js/queries/cluster_hex.js
  public/js/queries/count_locations.js
  public/js/queries/wkt.js
Labels: Code

#958 Location mvt cache
  lib/layer/decorate.mjs
  lib/location/decorate.mjs
  lib/location/get.mjs
  lib/ui/elements/drawing.mjs
  mod/location/delete.js
  mod/location/new.js
  mod/location/update.js
  mod/query.js
  mod/workspace/assignTemplates.js
  mod/workspace/templates/mvt_cache.js
  mod/workspace/templates/mvt_cache_delete_intersects.js
Labels: Code

#959 geometry entry draw & edit/modify
  lib/mapview/geoJSON.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/utils/style.mjs
Labels: Bug, Code

#960 Ensure table is defined when table=true passed
  lib/utils/queryParams.mjs
Labels: Bug

#962 Update queryParams.mjs
  lib/utils/queryParams.mjs
Labels: Bug

#964 fixed rtl plugin error on loading it twice
  lib/layer/format/maplibre.mjs
Labels: Bug

#965 Ensure tables response is always a string
  lib/location/get.mjs
Labels: Bug

#969 Assign point feature default style
  lib/utils/style.mjs
Labels: Bug

#973 Add cloudfront logger; signedURL short circuit; Await templates before merge.
  mod/provider/cloudfront.js
  mod/templates/_templates.js
Labels: Bug, Feature, Code

#980 Fix hover/hovers and label/labels bug
  lib/layer/decorate.mjs
Labels: Bug

#963 Dataview review
  lib/ui/Dataview.mjs
  lib/ui/locations/entries/dataview.mjs
  lib/ui/utils/Chart.mjs
  lib/ui/utils/Tabulator.mjs
  lib/ui/utils/tabulatorUtils.mjs
Labels: Feature

#981 Vector Cluster Changes
  lib/layer/format/_format.mjs
  lib/layer/format/vector.mjs
  lib/mapp.mjs
Labels: Bug
