Repository GEOLYTIX/xyz, pull requests merged in 2023-09, with the labels that each got.

#901 Bump Maplibre skypack import to v3.3.1
  lib/layer/format/maplibre.mjs
Labels: Code

#900 Do not delete interaction when finishing
  lib/mapview/interactions/draw.mjs
  lib/mapview/interactions/highlight.mjs
  lib/mapview/interactions/modify.mjs
  lib/mapview/interactions/zoom.mjs
Labels: Bug

#892 Remove SASS dependency; Bundle CSS with esbuild.
  package.json
  public/css/_button.css
  public/css/_colours.css
  public/css/_colours.scss
  public/css/_drawer.css
  public/css/_font.css
  public/css/_icons.css
  public/css/_inputs.css
  public/css/_layerview.css
  public/css/_locationview.css
  public/css/_mapp.css
  public/css/_tabview.css
  public/css/_ui.css
  public/css/mapp.css
  public/css/mapp.css.map
  public/css/ui.css
  public/css/ui.css.map
Labels: Code

#884 Create legendIcon for an icon array.
  lib/plugins.mjs
  lib/ui/elements/legendIcon.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/graduated.mjs
  public/css/_mapp.css
  public/css/mapp.css
  public/views/_default.js
Labels: Bug, Feature

#899 User Expiry Chceck
  api/api.js
  mod/templates/msgs.js
  mod/user/_user.js
  mod/user/login.js
  mod/user/register.js
  mod/user/verify.js
  public/views/_user.html
Labels: Bug

#905 Ensure that the draw callback exists.
  lib/layer/decorate.mjs
Labels: Bug

#909 Allow for empty roles update
  mod/user/update.js
  public/views/_user.html
Labels: Bug

#913 Enhancing Modal Interactivity
  lib/ui/elements/modal.mjs
  public/css/_ui.css
  public/css/ui.css
Labels: Code

#914 ol8.1 bump
  lib/utils/_utils.mjs
  lib/utils/featureFormats.mjs
  public/views/_default.html
Labels: Code

#916 Short circuit style assignment for icon with clusterScale
  lib/layer/themes/categorized.mjs
  lib/layer/themes/graduated.mjs
Labels: Bug

#918 Reload layer on label toggle
  lib/ui/layers/panels/style.mjs
Labels: Bug

#917 entry type:link as base for type:report
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/link.mjs
  lib/ui/locations/entries/report.mjs
Labels: Feature

#915 featureSource & getFeatures
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/mapview/interactions/draw.mjs
  lib/mapview/interactions/modify.mjs
  lib/mapview/interactions/snap.mjs
Labels: Feature

#924 Fix for Editing Locations without Dataviews
  lib/ui/locations/view.mjs
Labels: Bug

#919 Set label and hover; then replace children.
  lib/layer/decorate.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/panels/style.mjs
Labels: Bug, Feature

#923 Filter Labelling Bug
  lib/ui/elements/dropdown.mjs
Labels: Bug

#931 Feat icon updates
  lib/ui/locations/view.mjs
  public/css/_icons.css
  public/css/ui.css
  public/icons/icon-edit.svg
  public/icons/icon-save.svg
Labels: Feature

#929 Cloudinary image and documents method consolidation; Array value location update.
  lib/location/decorate.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/entries/documents.mjs
  lib/ui/locations/entries/images.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/locations/infoj.mjs
  lib/ui/locations/view.mjs
  mod/location/update.js
  mod/workspace/assignTemplates.js
  public/js/queries/set_field_array.js
Labels: Bug, Feature

#922 Vector layer
  lib/layer/format/mvt.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/vector_layer.mjs
  lib/utils/featureFormats.mjs
Labels: Feature

#934 Check whether locales object has own key for locale.
  mod/workspace/_workspace.js
Labels: Code, Security

#935 Ensure that the array param is a string
  api/api.js
Labels: Code, Security

#938 zoom interaction callback from default script
  public/views/_default.js
Labels: Bug

#932 Provide filter instead of entry
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
Labels: Code

#940 Ensure that the modify callback enables the highlight interaction.
  lib/ui/locations/entries/geometry.mjs
Labels: Bug
