Repository GEOLYTIX/xyz, pull requests merged in 2023-12, with the labels that each got.

#1015 Location queries
  api/api.js
  lib/layer/decorate.mjs
  lib/location/decorate.mjs
  lib/location/get.mjs
  lib/ui/elements/drawing.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/entries/defaults.mjs
  lib/ui/locations/entries/geometry.mjs
  mod/location/_location.js
  mod/location/delete.js
  mod/location/get.js
  mod/location/new.js
  mod/location/update.js
  mod/workspace/templates/_queries.js
  mod/workspace/templates/location_delete.js
  mod/workspace/templates/location_get.js
  mod/workspace/templates/location_new.js
  mod/workspace/templates/location_update.js
Labels: Code, Security

#1021 csvDownload params; toLocaleString
  lib/ui/elements/toolbar_el.mjs
  lib/ui/utils/tabulatorUtils.mjs
  lib/utils/csvDownload.mjs
Labels: Bug, Feature

#1026 layer.geomCurrent method
  lib/layer/decorate.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
Labels: Bug

#1016 Check query template roles
  mod/query.js
Labels: Feature, Code, Security

#1030 syncFields check
  lib/location/decorate.mjs
Labels: Bug

#1033 Layer failing to decorate must not be added to list
  lib/layer/decorate.mjs
  lib/mapview/addLayer.mjs
Labels: Bug

#1032 Make Admin Panel accessible on mobile
  public/views/_default.js
  public/views/_user.html
Labels: Feature

#1027 Provide layer key as snap option
  lib/mapview/interactions/snap.mjs
Labels: Feature

#1034 Assign entry.field from query response in infoj
  lib/ui/locations/infoj.mjs
Labels: Bug

#1037 entry type:tab chkbox
  lib/ui/locations/entries/tab.mjs
Labels: Bug

#1035 Update location_get query
  lib/location/get.mjs
  mod/workspace/templates/location_get.js
Labels: Code

#1042 Abort dataset gazetteer XHR
  lib/ui/Gazetteer.mjs
  lib/utils/gazetteer.mjs
Labels: Bug

#1041 nodemailer config from TRANSPORT environment variable
  mod/utils/mailer.js
  package.json
Labels: Bug

#1044 mvt and wkt query break with no fields being requested / vector format SRID warning
  lib/layer/format/vector.mjs
  mod/workspace/templates/mvt.js
  mod/workspace/templates/wkt.js
Labels: Bug

#1046 Don't merge workspace.locale with itself
  mod/workspace/cache.js
Labels: Bug
