Repository GEOLYTIX/xyz, pull requests merged in 2023-08, with the labels that each got.

#883 Cache OL Styles object
  lib/layer/Style.mjs
  lib/mapview/interactions/highlight.mjs
  lib/utils/style.mjs
Labels: Bug

#891 Enable maxlength edit config for type text
  lib/ui/locations/entries/text.mjs
  lib/ui/locations/entries/textarea.mjs
Labels: Feature

#896 Check for feature.set method
  lib/mapview/interactions/highlight.mjs
  lib/utils/style.mjs
Labels: Bug

#885 Add fetch mod; Remove module mod; Update mongo provider.
  api/api.js
  express.js
  mod/fetch.js
  mod/module.js
  mod/provider/_provider.js
  mod/provider/mongodb.js
  mod/workspace/_workspace.js
  mod/workspace/cache.js
Labels: Code

#897 added word break to locationview vals
  public/css/_locationview.scss
  public/css/ui.css
  public/css/ui.css.map
Labels: Bug

#887 Remove cloudinary sdk
  lib/ui/locations/entries/documents.mjs
  lib/ui/locations/entries/images.mjs
  mod/provider/cloudinary.js
  package.json
Labels: Code

#890 Update AWS S3 provider
  mod/provider/s3.js
  package.json
Labels: Code
