Repository GEOLYTIX/xyz, pull requests merged in 2023-02, with the labels that each got.

#591 Add New Icons
  package.json
  public/css/_icons.scss
  public/css/ui.css
  public/css/ui.css.map
  public/icons/icon-info-report.svg
  public/icons/icon-info.svg
  public/icons/icon-lightbulb.svg
  public/icons/icon-question-mark.svg
Labels: Feature

#593 Define default theme as string
  lib/layer/decorate.mjs
  lib/ui/layers/panels/style.mjs
Labels: Feature

#602 Wait for user admin table to be built in promise
  public/views/_user.html
Labels: Code

#583 Public folder and resources
  .gitignore
  express.js
  public/js/plugins/add_layer_view.js
  public/js/plugins/chart_entry.js
  public/js/plugins/cluster_panel.js
  public/js/plugins/compare_locations.js
  public/js/plugins/custom_filter.js
  public/js/plugins/download.js
  public/js/plugins/draw_circle_element.js
  public/js/plugins/geom_entry.js
  public/js/plugins/graduated_theme_slider.js
  public/js/plugins/hide_layers.js
  public/js/plugins/iconScaling.js
  public/js/plugins/isoline_pin.js
  public/js/plugins/layer_from_geojson.js
  public/js/plugins/measure_distance.js
  public/js/plugins/modify_context_menu.js
  public/js/plugins/mvt_select_tab.js
  public/js/plugins/pin_from_geom.js
  public/js/plugins/polygon_select.js
  public/js/plugins/reset_view.js
  public/js/plugins/screenshot.js
  public/js/plugins/table_entry.js
  public/js/plugins/update_entry.js
  public/js/plugins/user_filter.js
  public/js/plugins/visualAdjustment.js
  public/views/_default.html
  public/views/_user.html
  public/views/blog.html
  public/views/embedded.html
  public/views/epic.html
  public/views/login/_login_de.html
  public/views/login/_login_en.html
  public/views/login/_login_fr.html
  public/views/login/_login_ja.html
  public/views/login/_login_ko.html
  public/views/login/_login_pl.html
  public/views/login/_login_zh.html
  public/views/register/_register_de.html
  public/views/register/_register_en.html
  public/views/register/_register_fr.html
  public/views/register/_register_ja.html
  public/views/register/_register_ko.html
  public/views/register/_register_pl.html
  public/views/register/_register_zh.html
  public/workspaces/blog.json
  public/workspaces/dev.json
  public/workspaces/geodata.json
Labels: Code

#603 check for encoded cat keys in cat theme lookup
  lib/layer/themes/categorized.mjs
Labels: Code

#609 Fix for geojson setsource not cluster
  lib/layer/format/geojson.mjs
Labels: Bug

#613 Send 204 for empty mvt responses.
  mod/layer/mvt.js
Labels: Code

#605 update set headerfilter
  lib/ui/elements/dropdown.mjs
  lib/ui/elements/dropdown_multi.mjs
  lib/ui/utils/tabulatorUtils.mjs
  public/css/_inputs.scss
  public/css/ui.css
  public/css/ui.css.map
Labels: Feature

#601 enable ni filter entry and filter meta
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
Labels: Feature

#628 Lookup icon in cat theme for style assignment
  lib/ui/layers/legends/categorized.mjs
Labels: Code

#627 added possible cause and fix message to common exception
  lib/ui/layers/panels/filter.mjs
Labels: Code

#629 fixed dropdown issue on mobile
  public/css/_inputs.scss
  public/css/_tabview.scss
  public/css/ui.css
  public/css/ui.css.map
Labels: Bug
