Repository GEOLYTIX/xyz, pull requests merged in 2023-05, with the labels that each got.

#692 Fix for single geometries on a locations entry
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#752 WKT doesn't support resolution, so warn if config is wrong
  lib/layer/format/wkt.mjs
Labels: Code

#751 Replace version script with javascript version
  lib/mapp.mjs
  version.js
  version.sh
Labels: Code

#756 Add checks on if cluster and resolution are present to prevent error
  lib/layer/format/wkt.mjs
Labels: Bug

#758 Avoid type confusion through parameter tampering
  api/api.js
Labels: Security

#757 Check whether a geojson layer exists in workspace.
  mod/layer/geojson.js
Labels: Code

#761 Avoid type confusion through parameter tampering
  mod/query.js
Labels: Security

#760 Unit test initialise
  .github/workflows/node.js.yml
  package.json
  tests/mod/utils/clone.test.js
  tests/mod/utils/merge.test.js
  tests/mod/utils/roles.test.js
  tests/mod/utils/sqlFilter.test.js
  tests/mod/utils/validateRequestParams.test.js
Labels: Testing

#765 changed legend switch all button behaviour
  lib/ui/layers/legends/categorized.mjs
Labels: Code
