Repository GEOLYTIX/xyz, pull requests merged in 2024-12, with the labels that each got.

#1770 Infoj Order Can Be Specified on a Layer
  lib/ui/locations/infoj.mjs
  tests/lib/ui/locations/infoj.test.mjs
Labels: Bug

#1748 Temporal module;
  lib/ui/locations/entries/date.mjs
  lib/utils/_utils.mjs
  lib/utils/temporal.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/temporal.test.mjs
Labels: Code, Documentation

#1774 Adjust min width of 2nd div in location view grid column
  public/css/_locationview.css
  public/css/ui.css
Labels: Bug, CSS

#1775 CSV Download Fix when string includes commas
  lib/utils/csvDownload.mjs
Labels: Bug

#1780 syncFields array and documentation
  lib/location/decorate.mjs
Labels: Bug, Documentation
