Repository GEOLYTIX/xyz, pull requests merged in 2024-04, with the labels that each got.

#1200 mapp.utils.polygonIntersectFeatures
  lib/utils/_utils.mjs
  lib/utils/polygonIntersectFeatures.mjs
Labels: Feature

#1201 Bump Codi 🐶 to v0.0.15: Transition Buntime 🥟
  .github/workflows/unit_tests.yml
  package.json
  public/tests/_default.test.mjs
  public/tests/layer.test.mjs
  tests/mod/utils/roles.test.mjs
Labels: Testing

#1202 Update _mapview.mjs
  lib/mapview/_mapview.mjs
Labels: Code

#1203 Codi 🐶 Web Test Runner 🏃
  package.json
  public/tests/_default.test.mjs
  public/tests/layer.test.mjs
  public/views/_test.html
Labels: Testing

#1204 Update Codi Framework with Result Download
  package.json
  public/tests/_default.test.mjs
  public/tests/layer.test.mjs
  public/views/_test.html
Labels: Testing

#1205 Revert Icon Legend module
  lib/ui/elements/legendIcon.mjs
Labels: Bug

#1206 Modal Target Adjustment 🎯
  lib/ui/elements/modal.mjs
Labels: Bug

#1209 Update layer test
  public/tests/layer.test.mjs
Labels: Testing

#1210 Update Openlayers version and add warning for script loader.
  lib/mapp.mjs
  lib/utils/_utils.mjs
  public/tests/lib/layer/featureStyle.test.mjs
  public/views/_default.html
  public/views/_test.html
Labels: Code

#1216 Fix for Numeric Filter on field with no data
  lib/ui/layers/filters.mjs
Labels: Bug

#1217 Add locale.xss_check for infotip content
  lib/mapview/infotip.mjs
Labels: Code, Security

#1219 Update query docs
  mod/query.js
Labels: Documentation

#1220 Check and remove filter params from request for query templates without a filter placeholder.
  mod/query.js
Labels: Bug

#1222 ui element slider - prevent ranges from outside min/max range;
  lib/ui/elements/slider.mjs
Labels: Bug

#1218 Add st_distance_ab and st_intersects_ab query templates
  lib/ui/locations/infoj.mjs
  lib/utils/queryParams.mjs
  mod/workspace/templates/_queries.js
  mod/workspace/templates/st_distance_ab.js
  mod/workspace/templates/st_distance_ab_multiple.js
  mod/workspace/templates/st_intersects_ab.js
Labels: Feature, Plugin

#1223 Add layer.params.default_fields array
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
Labels: Feature

#1231 add ID to location_get warning
  lib/location/decorate.mjs
  lib/location/get.mjs
Labels: Code

#1236 Filter Fix
  lib/ui/layers/filters.mjs
Labels: Bug

#1235 Update mapp.mjs
  lib/mapp.mjs
Labels: Code
