Repository GEOLYTIX/xyz, pull requests merged in 2024-05, with the labels that each got.

#1241 Fix key value dictionary for the custom views
  lib/plugins/keyvalue_dictionary.mjs
Labels: Bug

#1242 Add SRC env subtitution to the getLayer Module
  mod/workspace/getLayer.js
Labels: Feature

#1244 style.contextFilter for tile format
  lib/layer/format/tiles.mjs
Labels: Feature

#1238 ui.elements.searchbox;
  lib/ui/elements/_elements.mjs
  lib/ui/elements/searchbox.mjs
  public/css/_inputs.css
  public/css/ui.css
Labels: Feature

#1233 Circle changes
  lib/ui/elements/drawing.mjs
Labels: Feature, Code

#1247 Gazetteer using searchbox element;
  lib/ui/Gazetteer.mjs
  public/css/_inputs.css
  public/css/ui.css
Labels: Bug, Code

#1255 Infoj Order Issue
  lib/ui/locations/infoj.mjs
Labels: Bug

#1251 Drawing Instructions Modal
  lib/mapview/interactions/draw.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/drawing.mjs
  lib/ui/elements/helpModal.mjs
  lib/ui/elements/modal.mjs
Labels: Bug, Feature

#1263 Pill component
  lib/ui/elements/_elements.mjs
  lib/ui/elements/pillComponent.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/pills.mjs
  public/css/_ui.css
  public/css/ui.css
Labels: Feature

#1266 `mapp.ui.elements.pills` Documentation and Rename 👀
  lib/ui/elements/_elements.mjs
  lib/ui/elements/pills.mjs
  lib/ui/locations/entries/pills.mjs
Labels: Code

#1267 Pills - value added to set;
  lib/ui/elements/pills.mjs
Labels: Code

#1272 Searchbox filter - now using pills and has updated dictionary;
  lib/ui/layers/filters.mjs
Labels: Feature

#1261 add input.invalid class
  lib/ui/elements/slider.mjs
  public/css/_inputs.css
  public/css/ui.css
Labels: RFC

#1278 Remove nanoid dependency
  package.json
Labels: Code

#1265 mvt_clone - reduce instances where the layer has to be removed or added.
  lib/ui/locations/entries/mvt_clone.mjs
  lib/ui/locations/entries/vector_layer.mjs
Labels: Bug

#1230 User IndexedDB
  api/api.js
  lib/plugins/_plugins.mjs
  lib/plugins/userIDB.mjs
  lib/utils/_utils.mjs
  lib/utils/userIndexedDB.mjs
  mod/user/cookie.js
  public/views/_default.html
Labels: Feature

#1279 css: .pill class now prevents user select;
  public/css/_ui.css
  public/css/ui.css
Labels: CSS

#1280 Pills - added remove method.
  lib/ui/elements/pills.mjs
Labels: Feature

#1285 Location Update: fix so it updates the field in the db
  mod/workspace/templates/location_update.js
Labels: Bug

#1284 dropdown_pills added to elements;
  lib/ui/elements/dropdown.mjs
  lib/ui/elements/pills.mjs
  lib/ui/layers/filters.mjs
Labels: Feature

#1286 Unsaved Changes CSS
  public/css/_colours.css
  public/css/_ui.css
  public/css/mapp.css
  public/css/ui.css
Labels: CSS

#1288 Add test for unequal arrays
  tests/mod/utils/merge.test.js
  tests/mod/utils/merge.test.mjs
  tests/mod/utils/roles.test.js
  tests/mod/utils/roles.test.mjs
Labels: Testing

#1281 Dropdown : Reverse based upon page position
  lib/ui/elements/dropdown.mjs
  public/css/_inputs.css
  public/css/ui.css
Labels: CSS
