Repository GEOLYTIX/xyz, pull requests merged in 2024-07, with the labels that each got.

#1352 Infoj: Group expanding on load
  lib/ui/locations/infoj.mjs
Labels: Bug

#1351 typedef documentation
  DOCUMENTATION.md
  api/README.md
  api/api.js
  express.js
  jsdoc_mapp.json
  jsdoc_xyz.json
  lib/README.md
  lib/hooks.mjs
  lib/layer/_layer.mjs
  lib/layer/decorate.mjs
  lib/layer/format/vector.mjs
  lib/layer/styleParser.mjs
  lib/layer/themes/basic.mjs
  lib/layer/themes/categorized.mjs
  lib/mapp.mjs
  lib/ui.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/layers/_layers.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/boolean.mjs
  lib/ui/locations/entries/key.mjs
  lib/ui/locations/entries/query_button.mjs
  lib/ui/locations/entries/title.mjs
  lib/ui/utils/_utils.mjs
  lib/utils/_utils.mjs
  mod/README.md
  mod/fetch.js
  mod/query.js
  mod/view.js
Labels: Documentation

#1361 Fix expiry insert
  api/api.js
  mod/user/register.js
Labels: Bug, Documentation

#1360 Disable location view for blocking api request from geometry entry me…
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1353 Reverse theme style assignment; Check for useridb flag in locale.
  lib/layer/styleParser.mjs
  public/views/_default.html
Labels: Bug, Feature

#1363 Lookup theme from string
  lib/layer/styleParser.mjs
Labels: Bug

#1365 zero config bug and secret
  lib/ui/elements/dialog.mjs
  mod/user/auth.js
  mod/workspace/cache.js
  public/css/_ui.css
  public/css/ui.css
  public/views/_default.html
Labels: Bug

#1366 infoj_skip in layer decorator
  lib/layer/decorate.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/locations/infoj.mjs
Labels: Code, Documentation

#1368 location.create() method as replacement for draw interaction callback with defaults/default_fields location updates.
  lib/layer/decorate.mjs
  lib/location/_location.mjs
  lib/location/create.mjs
  lib/location/decorate.mjs
  lib/mapview/_mapview.mjs
  lib/mapview/interactions/draw.mjs
  lib/ui/elements/drawing.mjs
Labels: Feature, Code, Documentation

#1362 Replace legend children elements instead of legend element.
  lib/layer/_layer.mjs
  lib/layer/featureFields.mjs
  lib/layer/format/vector.mjs
  lib/ui/elements/drawer.mjs
  lib/ui/elements/legendIcon.mjs
  lib/ui/layers/_layers.mjs
  lib/ui/layers/legends/basic.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/distributed.mjs
  lib/ui/layers/legends/graduated.mjs
  lib/ui/layers/panels/style.mjs
  lib/utils/olStyle.mjs
Labels: Bug, Code, Documentation

#1369 Review and document entry.default, entry.nullValue, and defaults.
  lib/ui/locations/entries/defaults.mjs
  lib/ui/locations/infoj.mjs
Labels: Code, Documentation

#1373 Check for ACL module being a function.
  mod/user/acl.js
  mod/user/add.js
  mod/user/cookie.js
  mod/user/delete.js
  mod/user/key.js
  mod/user/log.js
  mod/user/register.js
  mod/user/saml.js
  mod/user/update.js
  mod/user/verify.js
  public/views/_default.html
Labels: Bug, Security

#1367 Dialog headerDrag
  lib/ui/elements/dialog.mjs
  public/css/_ui.css
  public/css/ui.css
  public/views/_default.html
Labels: Bug, Feature

#1380 Log error instead of warning for missing entry.type in infoj check ; log error instead of warning for invalid format.
  lib/mapview/addLayer.mjs
  lib/ui/locations/infoj.mjs
Labels: Bug, Documentation

#1375 Dataview entry exception for show method.
  lib/ui/locations/entries/dataview.mjs
Labels: Bug

#1376 feature_info highlight plugin; highlight popup; mapview typedef
  lib/mapview/_mapview.mjs
  lib/mapview/interactions/highlight.mjs
  lib/plugins/_plugins.mjs
  lib/plugins/feature_info.mjs
  public/css/_icons.css
  public/css/ui.css
  public/icons/icon-feature-info.svg
Labels: Feature, Code, Plugin, Documentation

#1378 Loadplugins error
  lib/utils/loadPlugins.mjs
Labels: Bug

#1379 Enable delete from hook / url param
  public/views/_default.html
Labels: Bug, Feature

#1377 Only check highlight style if typeof object
  lib/layer/styleParser.mjs
  tests/lib/layer/styleParser.test.mjs
Labels: Bug

#1383 Assign getLayer template error message; catch and log error in addLayer
  lib/mapview/addLayer.mjs
  mod/workspace/getLayer.js
Labels: Bug

#1387 Remove dev console.log() from cookie module.
  mod/user/cookie.js
Labels: Bug

#1389 check on falsy values; not length
  lib/ui/locations/infoj.mjs
Labels: Bug

#1398 Log original error message for load plugin errors.
  lib/utils/loadPlugins.mjs
Labels: Bug

#1391 Assign location.style to vector_layer entry
  lib/ui/locations/entries/vector_layer.mjs
Labels: Bug, Documentation

#1385 Allow for array updates with text entry arraySeparator
  lib/ui/locations/entries/text.mjs
Labels: Feature, Documentation

#1395 Fix issue where dataview is disconnected from layer object.
  lib/ui/layers/panels/dataviews.mjs
Labels: Bug
