Repository GEOLYTIX/xyz, pull requests merged in 2024-01, with the labels that each got.

#1053 Draw on layer without infoj
  lib/location/get.mjs
  mod/workspace/templates/location_get.js
  mod/workspace/templates/mvt.js
Labels: Bug

#1045 numeric input formatter
  lib/ui/locations/entries/numeric.mjs
Labels: Feature

#1056 Allow object default layer filter
  mod/query.js
  mod/utils/sqlFilter.js
Labels: Feature

#1058 bump esbuild dev dependency to 0.19.11
  package.json
Labels: Code

#1057 Distinct in/ni filter
  lib/ui/layers/filters.mjs
Labels: Bug, Feature

#1063 Failed to load workspace
  mod/provider/file.js
  mod/provider/getFrom.js
  mod/query.js
  mod/utils/languageTemplates.js
  mod/workspace/_workspace.js
  mod/workspace/cache.js
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
Labels: Bug

#1062 Clear highlight interaction on mouseout.
  lib/mapview/interactions/highlight.mjs
Labels: Feature

#1065 Update to verify the absence of a user in the Access Control List (ACL).
  mod/user/fromACL.js
Labels: Bug

#1043 simple-statistics; featureFormats & featureFields
  README.md
  lib/layer/_layer.mjs
  lib/layer/featureFields.mjs
  lib/layer/featureFormats.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/layer/themes/categorized.mjs
  lib/layer/themes/graduated.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/graduated.mjs
  lib/utils/_utils.mjs
  package.json
Labels: Feature, Code

#1068 Get scale_bar from locale
  lib/mapview/_mapview.mjs
  public/views/_default.js
Labels: Code

#1072 round shorthand for formatterParams.options.maximumFractionDigits
  lib/ui/locations/entries/numeric.mjs
Labels: Feature

#1075 Spelling mistake
  lib/ui/locations/view.mjs
Labels: Bug

#1074 Typeof `function` check
  lib/layer/decorate.mjs
  public/views/_default.js
Labels: Bug

#1076 mapview.extent
  lib/mapview/_mapview.mjs
Labels: Code

#1070 Provided missing gazetteer to Coordinates Entry
  lib/layer/decorate.mjs
  lib/location/decorate.mjs
  lib/mapview/fitView.mjs
  lib/ui/Gazetteer.mjs
  lib/utils/gazetteer.mjs
Labels: Bug

#1077 mapp.host
  lib/mapp.mjs
  lib/mapview/_mapview.mjs
  public/views/_default.js
Labels: Feature, Code

#1079 Load plugins in mapview creation
  lib/mapview/_mapview.mjs
  public/views/_default.js
Labels: Feature, Code

#1080 Update mapview.geoJSON method
  lib/layer/featureFormats.mjs
  lib/mapview/geoJSON.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/pin.mjs
Labels: Feature, Code

#1081 location.getInfoj
  lib/location/_location.mjs
  lib/location/get.mjs
  lib/utils/queryParams.mjs
Labels: Feature, Code

#1092 Provide fallback when host is empty string
  lib/ui/Dataview.mjs
  lib/ui/locations/entries/dataview.mjs
  lib/ui/locations/entries/mvt_clone.mjs
  lib/ui/locations/entries/vector_layer.mjs
  lib/ui/locations/infoj.mjs
Labels: Bug

#1094 Re-drawing Geometry Fix
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1083 provide string array argument as filter for ui.location.infoj(loc, [])
  lib/ui/locations/infoj.mjs
Labels: Feature

#1088 Move default btn methods to plugins
  lib/plugins.mjs
  public/views/_default.js
Labels: Code

#1095 Get array of layer objects instead of layer keys
  mod/workspace/_workspace.js
  public/views/_default.js
Labels: Feature, Code

#1097 Replace custom clone util with structuredClone
  lib/layer/Style.mjs
  lib/layer/themes/graduated.mjs
  lib/utils/_utils.mjs
  lib/utils/clone.mjs
Labels: Code

#1096 Check whether a plugin string endsWith some value from an array
  lib/utils/loadPlugins.mjs
Labels: Feature

#1099 Remove unnecessary checks
  mod/workspace/_workspace.js
  mod/workspace/getLocale.js
Labels: Bug

#1098 Mapview attribution
  lib/mapview/_mapview.mjs
  lib/mapview/attribution.mjs
  public/css/_mapp.css
  public/css/mapp.css
  public/views/_default.html
  public/views/_default.js
Labels: Feature, Code

#1103 Allow to define the attribution target
  lib/mapview/attribution.mjs
  public/views/_default.js
Labels: Bug
