Repository GEOLYTIX/xyz, pull requests merged in 2024-06, with the labels that each got.

#1290 Locations Delete
  mod/query.js
  mod/workspace/getLayer.js
  mod/workspace/templates/_queries.js
  mod/workspace/templates/locations_delete.js
Labels: Feature

#1291 Deep merge [clone] locale for storage in userIDB
  lib/layer/decorate.mjs
  lib/plugins/userIDB.mjs
  lib/utils/merge.mjs
  tests/mod/utils/merge.test.mjs
Labels: Feature

#1295 Test Updates
  tests/mod/utils/reqHost.test.mjs
  tests/mod/utils/sqlFilter.test.js
  tests/mod/utils/sqlFilter.test.mjs
  tests/mod/utils/validateRequestParams.test.js
  tests/mod/utils/validateRequestParams.test.mjs
Labels: Testing

#1294 Update val-changed CSS
  public/css/_ui.css
  public/css/ui.css
Labels: Bug, CSS

#1293 Text Entry - distinct query fix field fix
  lib/ui/locations/entries/text.mjs
Labels: Bug

#1292 Ability to Test for the creation/ deletion of locations
  public/tests/layer.test.mjs
Labels: Feature, Testing

#1297 GitHub Issue and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ISSUE_TEMPLATE.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#1298 Update Administration Panel
  public/views/_user.html
Labels: Feature, CSS

#1299 JSON Entries - Editing distinct query fix
  lib/ui/layers/panels/filter.mjs
  lib/ui/locations/entries/text.mjs
  mod/workspace/templates/distinct_values_json.js
Labels: Bug

#1282 Request geometry from API
  lib/layer/featureFormats.mjs
  lib/mapview/_mapview.mjs
  lib/mapview/geoJSON.mjs
  lib/mapview/geometry.mjs
  lib/ui/locations/_locations.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/vector_layer.mjs
  lib/ui/locations/infoj.mjs
  lib/ui/locations/view.mjs
  mod/query.js
  mod/workspace/templates/geojson.js
  mod/workspace/templates/location_get.js
Labels: Bug, Feature, Code

#1302 Filter Min = 0 Fix
  lib/ui/layers/filters.mjs
  mod/workspace/templates/_queries.js
  mod/workspace/templates/field_minmax.js
Labels: Bug, Code

#1307 Update docs and allow for numeric filter value.
  lib/ui/elements/pills.mjs
  lib/ui/elements/searchbox.mjs
  lib/ui/layers/filters.mjs
Labels: Bug, Code, Documentation

#1313 Query Button PR
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/query_button.mjs
Labels: Feature, Plugin

#1317 PR and Issue Template Fix
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bug, Documentation

#1308 Modal Dialog element 🖼️
  lib/ui/elements/_elements.mjs
  lib/ui/elements/dialog.mjs
  lib/ui/elements/drawing.mjs
  lib/ui/elements/helpDialog.mjs
  lib/ui/elements/modal.mjs
  public/css/_ui.css
  public/css/ui.css
  public/tests/_default.test.mjs
  public/views/_default.html
Labels: Feature, Code

#1315 entry type:key to return layer display toggle
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/key.mjs
  lib/ui/locations/entries/title.mjs
  public/css/_locationview.css
  public/css/ui.css
Labels: Feature, CSS

#1310 ui.elements.input
  lib/ui/elements/_elements.mjs
  lib/ui/elements/numericFormatter.mjs
  lib/ui/elements/numericInput.mjs
  lib/ui/locations/entries/numeric.mjs
  public/css/_inputs.css
  public/css/ui.css
Labels: Feature, UI

#1324 The style must be assigned before the highlight.
  lib/layer/styleParser.mjs
Labels: Bug

#1325 Ensure that each entry has a key.
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/mvt_clone.mjs
  lib/ui/locations/entries/vector_layer.mjs
  lib/ui/locations/infoj.mjs
Labels: Bug, Code

#1326 Ensure that the style.zIndex is only used in the olStyle module
  lib/layer/format/googleMapTiles.mjs
  lib/layer/format/maplibre.mjs
  lib/layer/format/mbtiles.mjs
  lib/layer/format/tiles.mjs
  lib/layer/format/vector.mjs
Labels: Bug, Code

#1336 Check on entry.Layer needs to happen before assigning entry.Layer.zIndex
  lib/ui/locations/entries/mvt_clone.mjs
Labels: Bug

#1338 maplibre and style.zIndex
  lib/layer/format/googleMapTiles.mjs
  lib/layer/format/maplibre.mjs
  lib/layer/format/mbtiles.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/tiles.mjs
  lib/layer/format/vector.mjs
  lib/layer/styleParser.mjs
Labels: Bug

#1332 Don't spread style when style object is empty
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1340 Provider Sign Authentication
  api/api.js
Labels: Bug, Security

#1341 Queryselector fails with data-id beginning with zero
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1264 Review _user API mod
  api/api.js
  mod/user/_user.js
  mod/user/acl.js
  mod/user/add.js
  mod/user/admin.js
  mod/user/auth.js
  mod/user/cookie.js
  mod/user/delete.js
  mod/user/fromACL.js
  mod/user/key.js
  mod/user/list.js
  mod/user/log.js
  mod/user/login.js
  mod/user/register.js
  mod/user/saml.js
  mod/user/token.js
  mod/user/update.js
  mod/user/verify.js
  mod/utils/reqHost.js
  public/views/_user.html
Labels: Bug, Feature, Code, Security

#1343 Boolean entry - unnecessary label after symbol
  lib/ui/locations/entries/boolean.mjs
  public/tests/_default.test.mjs
  public/tests/layer.test.mjs
  public/tests/lib/ui/_ui.test.mjs
  public/tests/lib/ui/locations/entries/boolean.test.mjs
Labels: Bug

#1331 Cluster style parser and spread.
  lib/layer/featureStyle.mjs
  lib/layer/styleParser.mjs
  lib/layer/themes/basic.mjs
  lib/layer/themes/categorized.mjs
  lib/layer/themes/graduated.mjs
  lib/utils/olStyle.mjs
  tests/lib/layer/styleParser.test.mjs
Labels: Bug

#1345 Add documentation.md to repository.
  DOCUMENTATION.md
Labels: Documentation

#1346 Geometry - Configurable Labels
  lib/ui/locations/entries/geometry.mjs
Labels: Bug, Feature

#1322 UI elements input formatter
  lib/ui/elements/_elements.mjs
  lib/ui/elements/numericFormatter.mjs
  lib/ui/elements/numericInput.mjs
  lib/ui/elements/slider_ab.mjs
  lib/ui/layers/filters.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/utils/tabulator.mjs
  lib/utils/_utils.mjs
  lib/utils/numericFormatter.mjs
Labels: Bug, Code, UI
