Repository GEOLYTIX/xyz, pull requests merged in 2024-08, with the labels that each got.

#1381 Numeric input css fix
  lib/location/decorate.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/numericInput.mjs
  lib/ui/elements/slider.mjs
  lib/ui/elements/slider_ab.mjs
  lib/ui/layers/filters.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/locations/view.mjs
  lib/utils/_utils.mjs
  lib/utils/numericFormatter.mjs
Labels: Bug, Code, Documentation, UI, v4.9.2

#1394 Test example
  .gitignore
  TESTING.md
  codi.json
  express.js
  jsdoc_test.json
  lib/layer/changeEnd.mjs
  lib/layer/decorate.mjs
  lib/layer/styleParser.mjs
  package.json
  public/tests/_default.test.mjs
  public/tests/lib/layer/Style.mjs
  public/views/_test.html
  public/views/_user.html
  tests/browser/_base.test.mjs
  tests/browser/integrity.test.mjs
  tests/browser/layer.test.mjs
  tests/browser/local.test.mjs
  tests/lib/dictionaries/_dictionaries.test.mjs
  tests/lib/layer/_layer.test.mjs
  tests/lib/layer/changeEnd.test.mjs
  tests/lib/layer/decorate.test.mjs
  tests/lib/layer/fade.test.mjs
  tests/lib/layer/featureFields.test.mjs
  tests/lib/layer/featureFilter.test.mjs
  tests/lib/layer/featureFormats.test.mjs
  tests/lib/layer/featureHover.test.mjs
  tests/lib/layer/featureStyle.test.mjs
  tests/lib/layer/styleParser.test.mjs
  tests/lib/location/_location.test.mjs
  tests/lib/location/create.test.mjs
  tests/lib/location/decorate.test.mjs
  tests/lib/location/get.test.mjs
  tests/lib/location/nnearest.test.mjs
  tests/lib/mapview/_mapview.test.mjs
  tests/lib/mapview/addLayer.test.mjs
  tests/lib/mapview/allfeatures.test.mjs
  tests/lib/mapview/attribution.test.mjs
  tests/lib/mapview/fitView.test.mjs
  tests/lib/mapview/geojson.test.mjs
  tests/lib/mapview/geometry.test.mjs
  tests/lib/mapview/getBounds.test.mjs
  tests/lib/mapview/infotip.test.mjs
  tests/lib/mapview/locate.test.mjs
  tests/lib/mapview/popup.test.mjs
  tests/lib/ui/_ui.test.mjs
  tests/lib/ui/locations/entries/boolean.test.mjs
  tests/mod/utils/reqHost.test.mjs
  tests/utils/delay.js
  tests/utils/view.js
  tests/workspace.json
Labels: Testing, v4.10.0

#1404 Vector layer format error handling
  lib/layer/featureFormats.mjs
  lib/layer/format/vector.mjs
Labels: Bug, Code, Documentation, v4.10.1

#1413 Do not assign window as caller for vector layer reload method
  lib/layer/format/vector.mjs
Labels: Bug, v4.10.1

#1396 findlast keyvalue dictionary entry for multiple options.
  lib/plugins/keyvalue_dictionary.mjs
  tests/browser/local.test.mjs
  tests/lib/dictionaries/_dictionaries.test.mjs
  tests/lib/dictionaries/baseDictionary.test.mjs
  tests/lib/dictionaries/keyValueDictionary.test.mjs
  tests/workspace.json
Labels: Feature, v4.10.1

#1402 Add details param for workspace/roles request.
  mod/utils/roles.js
  mod/workspace/_workspace.js
  tests/browser/_api.test.mjs
  tests/browser/local.test.mjs
  tests/mod/utils/roles.test.mjs
  tests/workspace.json
Labels: Feature, v4.10.1

#1418 Prevent this being the location.view element
  lib/ui/locations/view.mjs
Labels: Bug

#1417 Update Integrity test
  public/tests/_base.test.mjs
  public/tests/integrity.test.mjs
  public/tests/layer.test.mjs
  public/views/_test.html
  tests/browser/local.test.mjs
Labels: Bug, v4.10.1

#1400 Bump aws-sdk modules
  package.json
Labels: Code, Security, v4.10.1

#1407 bump ol lib
  lib/mapp.mjs
  public/views/_default.html
  public/views/_test.html
Labels: Code, v4.10.1

#1411 Dataview location stroke color;
  lib/ui/locations/entries/dataview.mjs
Labels: Bug, v4.10.1

#1408 Geometry entry draw callback
  lib/ui/elements/drawing.mjs
  lib/ui/locations/entries/geometry.mjs
Labels: Bug, Documentation, v4.10.1

#1412 Link Button Plugin
  lib/plugins/_plugins.mjs
  lib/plugins/link_button.mjs
  public/css/_font.css
  public/css/ui.css
  tests/browser/local.test.mjs
  tests/plugins/_plugins.test.mjs
  tests/plugins/link_button.test.mjs
  tests/workspace.json
Labels: Plugin, v4.10.1

#1392 Changes required to implement user update with payload;
  express.js
  lib/ui/elements/pills.mjs
  lib/utils/_utils.mjs
  lib/utils/xhr.mjs
  mod/user/update.js
  tests/browser/local.test.mjs
  tests/mod/user/_user.test.js
  tests/mod/user/update.test.mjs
Labels: Bug, Feature, Code, Security, v4.10.1

#1422 Default view dialog fixes
  lib/ui/elements/dialog.mjs
  lib/ui/elements/helpDialog.mjs
  public/tests/_base.test.mjs
  public/views/_default.html
  tests/workspace.json
Labels: Bug, v4.10.1

#1419 elements.slider val/value property and layer.style.opacity slider element callback
  lib/ui/elements/slider.mjs
  lib/ui/layers/panels/style.mjs
  lib/ui/locations/entries/numeric.mjs
  tests/browser/local.test.mjs
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/slider.test.mjs
  tests/workspace.json
Labels: Bug, v4.10.1

#1425 Assign roles onto update_user object
  mod/user/update.js
Labels: Bug

#1424 entry without node in valChangeMethod on a new location.
  lib/ui/locations/view.mjs
Labels: Bug

#1429 Fix language differences
  lib/ui/elements/contextMenu.mjs
  lib/ui/elements/drawing.mjs
  lib/ui/layers/listview.mjs
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/layers/panels/draw.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/layers/panels/style.mjs
  lib/ui/layers/view.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/link.mjs
  lib/ui/locations/entries/pin.mjs
  lib/ui/locations/entries/text.mjs
  lib/ui/locations/listview.mjs
  lib/ui/locations/view.mjs
  public/tests/_base.test.mjs
  public/views/_default.html
Labels: Bug, v4.10.1

#1428 Update user - only add `field` if present in params
  mod/user/update.js
Labels: Bug, v4.10.1

#1427 Update JSDocs definition in infoj module; Location typedef
  DOCUMENTATION.md
  lib/location/decorate.mjs
  lib/ui/locations/infoj.mjs
  lib/utils/merge.mjs
  lib/utils/paramString.mjs
  lib/utils/xhr.mjs
Labels: Documentation, v4.10.1

#1433 Test Workspace rework
  tests/assets/layers/scratch/infoj.json
  tests/assets/layers/scratch/layer.json
  tests/assets/layers/scratch/style.json
  tests/assets/layers/template_test.json
  tests/assets/layers/uk_geometries/infoj.json
  tests/assets/layers/uk_geometries/layer.json
  tests/lib/layer/decorate.test.mjs
  tests/mod/user/update.test.mjs
  tests/workspace.json
Labels: Code

#1436 icon scaling test assets
  tests/assets/layers/scratch/layer.json
  tests/assets/layers/scratch/style.json
  tests/assets/layers/scratch/style_icon_scaling.json
  tests/assets/queries/icon_scaling_scratch.sql
  tests/workspace.json
Labels: Code

#1414 Add icon_scaling to featureStyle methods.
  lib/layer/featureFields.mjs
  lib/layer/featureFormats.mjs
  lib/layer/featureStyle.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/layer/styleParser.mjs
  lib/ui/elements/legendIcon.mjs
  lib/utils/olStyle.mjs
  public/tests/_base.test.mjs
  tests/assets/layers/scratch/style_icon_scaling.json
  tests/browser/local.test.mjs
  tests/lib/layer/fade.test.mjs
  tests/lib/layer/featureFormats.test.mjs
  tests/lib/layer/featureStyle.test.mjs
  tests/mod/query.test.mjs
  tests/workspace.json
Labels: Feature, Code, Documentation, v4.10.1

#1437 Create proxy module for mapp.dictionary to check for mapp.language and lookup key
  lib/dictionaries/_dictionaries.mjs
  lib/dictionaries/_dictionary.mjs
  lib/mapp.mjs
  public/views/_default.html
  public/views/_test.html
  tests/browser/local.test.mjs
  tests/lib/dictionaries/_dictionaries.test.mjs
  tests/lib/dictionaries/unknownLanguageTest.test.mjs
Labels: Bug, Code

#1439 Update view and languageTemplates modules
  mod/utils/languageTemplates.js
  mod/view.js
Labels: Code, Documentation

#1445 Circle Configuration Fixes; Min Max Based on Units
  lib/ui/elements/drawing.mjs
Labels: Bug, v4.10.1

#1446 User update req.body check for Vercel deployments ▲
  mod/user/update.js
  public/views/_user.html
Labels: Bug, v4.10.1

#1448 Check whether user exists before language
  public/views/_default.html
Labels: Bug
