Repository GEOLYTIX/xyz, pull requests merged in 2024-09, with the labels that each got.

#1447 Missing HelpDialog for Editing a Geometry Editing
  lib/ui/locations/entries/geometry.mjs
Labels: Feature, v4.10.1

#1453 Location mock
  lib/location/get.mjs
  tests/assets/layers/location_mock/infoj.json
  tests/assets/layers/location_mock/layer.json
  tests/assets/queries/get_location_mock.sql
  tests/browser/local.test.mjs
  tests/lib/location/get.test.mjs
  tests/workspace.json
Labels: Feature, Testing

#1432 Add src test method to workspace module.
  mod/workspace/_workspace.js
  public/tests/layer.test.mjs
Labels: Feature

#1451 numericChecks method for slider_ab element.
  lib/ui/elements/numericInput.mjs
  lib/ui/elements/slider_ab.mjs
Labels: Bug, Feature, v4.10.1

#1438 locale.locations: records, style, and pinStyle for locations listview
  lib/mapview/geometry.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/pin.mjs
  lib/ui/locations/listview.mjs
  lib/utils/olStyle.mjs
  tests/assets/layers/location_mock/infoj.json
  tests/assets/queries/get_location_mock.sql
  tests/browser/local.test.mjs
  tests/lib/location/get.test.mjs
  tests/lib/ui/locations/entries/_entires.test.mjs
  tests/lib/ui/locations/entries/pin.test.mjs
  tests/lib/ui/locations/listview.test.mjs
  tests/utils/location.js
  tests/workspace.json
Labels: Feature, Documentation, v4.10.1

#1431 Create ui.elements.layerStyle module
  lib/ui/elements/_elements.mjs
  lib/ui/elements/layerStyle.mjs
  lib/ui/elements/slider.mjs
  lib/ui/elements/slider_ab.mjs
  lib/ui/layers/panels/style.mjs
  tests/browser/local.test.mjs
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/layerStyle.test.mjs
Labels: Bug, Feature, Code, v4.10.1

#1454 Only update dataview with activateUpdate or no data.
  lib/ui/Tabview.mjs
Labels: Feature, RFC, v4.11.0

#1459 Remove reference for mapButton used for user admin only.
  public/views/_default.html
Labels: UI

#1462 Only check obj key template if not implicit
  DOCUMENTATION.md
  mod/workspace/getLocale.js
  mod/workspace/mergeTemplates.js
Labels: Bug

#1472 Add theme fields array to fieldsArray
  lib/layer/featureFields.mjs
  package.json
  public/views/_test.html
  tests/browser/local.test.mjs
  tests/lib/layer/featureFields.test.mjs
Labels: Bug

#1477 Remove geometry Layers[] from array
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/pin.mjs
  tests/browser/local.test.mjs
  tests/lib/ui/locations/entries/_entires.test.mjs
  tests/lib/ui/locations/entries/geometry.test.mjs
Labels: Bug

#1479 Fix placeholder spelling and size check
  lib/ui/elements/dropdown.mjs
Labels: Bug

#1468 addlayer to allow for single layer to be added.
  lib/mapview/addLayer.mjs
  tests/browser/local.test.mjs
  tests/lib/mapview/addLayer.test.mjs
Labels: Bug, Feature, Testing, Documentation, v4.11.0

#1485 highlight interaction render and getLocation
  lib/hooks.mjs
  lib/location/get.mjs
  lib/location/nnearest.mjs
  lib/mapview/allFeatures.mjs
  lib/mapview/interactions/highlight.mjs
  public/css/_mapp.css
  public/css/mapp.css
Labels: Bug, Code, Documentation

#1488 Changed z-index on .dropdown ul;
  public/css/_inputs.css
  public/css/ui.css
Labels: CSS

#1480 Allow for custom min max query template.
  lib/ui/layers/filters.mjs
  tests/assets/queries/minmax_mock.sql
  tests/browser/local.test.mjs
  tests/lib/ui/layers/_layers.test.mjs
  tests/lib/ui/layers/filters.test.mjs
  tests/lib/ui/locations/entries/geometry.test.mjs
  tests/workspace.json
Labels: Feature

#1490 The layer style cache should be optional.
  lib/layer/featureStyle.mjs
  lib/layer/styleParser.mjs
Labels: Bug, Feature, Code, v4.11.0

#1492 Fix workspace test to include user for roles check
  mod/workspace/_workspace.js
Labels: Bug, v4.11.0

#1491 getfeature call from highlight click
  lib/mapview/interactions/highlight.mjs
Labels: Bug, v4.11.0

#1493 Add data-id to layer view element
  lib/ui/layers/view.mjs
Labels: Feature, v4.11.0

#1482 dataview and tabview module documentation
  lib/ui/Dataview.mjs
  lib/ui/Tabview.mjs
  lib/ui/utils/_utils.mjs
  lib/ui/utils/jsonDataview.mjs
  tests/assets/dataviews/dataviews_json.json
  tests/browser/local.test.mjs
  tests/lib/ui/Tabview.test.mjs
  tests/lib/ui/_ui.test.mjs
  tests/lib/ui/locations/entries/_entries.test.mjs
  tests/workspace.json
Labels: Bug, Code, Documentation, v4.11.0

#1495 Template rework and Unused Check
  mod/workspace/_workspace.js
  mod/workspace/cache.js
  mod/workspace/mergeTemplates.js
  tests/assets/styles/template_style.json
Labels: Bug, Feature, Testing, v4.11.0

#1471 Set icon_scaling defaults; warn for plugin config; numcheck callback.
  lib/layer/styleParser.mjs
  lib/ui/elements/layerStyle.mjs
  lib/ui/elements/numericInput.mjs
  tests/assets/layers/scratch/layer.json
  tests/assets/layers/scratch/style.json
Labels: Bug, Plugin, v4.11.0

#1501 Pass filter to minmax
  lib/ui/layers/filters.mjs
  tests/lib/ui/layers/filters.test.mjs
Labels: Bug, v4.11.0

#1500 Prevent Selection of a Location on a Layer with no Infoj
  lib/location/get.mjs
  tests/lib/location/get.test.mjs
  tests/workspace.json
Labels: Bug, v4.11.0

#1505 Add back & document cluster featureformat
  lib/layer/featureFormats.mjs
  lib/layer/format/vector.mjs
  tests/browser/local.test.mjs
  tests/lib/layer/format/_format.test.mjs
  tests/lib/layer/format/vector.test.mjs
  tests/workspace.json
Labels: Bug, Code, v4.11.0

#1506 Match equals
  mod/utils/sqlFilter.js
  tests/mod/utils/sqlFilter.test.mjs
Labels: Code, Documentation, v4.11.0

#1508 Infoj Order Correction
  lib/ui/locations/infoj.mjs
  tests/browser/local.test.mjs
  tests/lib/ui/locations/_locations.test.mjs
  tests/lib/ui/locations/infoj.test.mjs
Labels: Bug, v4.11.0

#1502 Add template typedef review usage test
  mod/workspace/_workspace.js
  mod/workspace/cache.js
  mod/workspace/getTemplate.js
  mod/workspace/mergeTemplates.js
  tests/workspace.json
Labels: Documentation, v4.11.0

#1484 mapp.ui.elements.alert/ confirm methods
  lib/dictionaries/en.mjs
  lib/location/decorate.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/alert.mjs
  lib/ui/elements/confirm.mjs
  lib/ui/elements/dialog.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/view.mjs
  public/css/_ui.css
  public/css/ui.css
  tests/browser/local.test.mjs
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/alert.test.mjs
  tests/lib/ui/elements/confirm.test.mjs
  tests/lib/ui/elements/dialog.test.mjs
  tests/lib/ui/elements/slider.test.mjs
Labels: Feature, v4.11.0

#1503 numericFormatter locale issue
  lib/ui/elements/numericInput.mjs
  lib/ui/elements/slider.mjs
  lib/ui/elements/slider_ab.mjs
  lib/utils/numericFormatter.mjs
  tests/assets/infoj/template_infoj.json
  tests/browser/local.test.mjs
  tests/lib/layer/format/vector.test.mjs
  tests/lib/ui/elements/alert.test.mjs
  tests/lib/ui/layers/filters.test.mjs
  tests/lib/ui/locations/infoj.test.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/numericFormatter.test.mjs
  tests/mod/workspace/_workspace.test.mjs
  tests/workspace.json
Labels: Bug, Testing, v4.11.0
