Repository GEOLYTIX/xyz, pull requests merged in 2024-11, with the labels that each got.

#1633 Remove data-id assignment for layer-view element
  lib/ui/layers/listview.mjs
  lib/ui/layers/view.mjs
Labels: Code, UI

#1632 Tabview Expanded more by Default
  public/views/_default.html
Labels: CSS, v4.12.2

#1645 Remove legacy node-fetch and document mod/cloudfront ☁️
  mod/provider/cloudfront.js
Labels: Bug, Code

#1588 layer query and templates
  mod/query.js
  mod/workspace/getLayer.js
  mod/workspace/templates/_queries.js
  mod/workspace/templates/cluster.js
  mod/workspace/templates/cluster_hex.js
  mod/workspace/templates/geojson.js
  mod/workspace/templates/get_last_location.js
  mod/workspace/templates/get_nnearest.js
  mod/workspace/templates/infotip.js
  mod/workspace/templates/layer_extent.js
  mod/workspace/templates/location_count.js
  mod/workspace/templates/location_delete.js
  mod/workspace/templates/location_get.js
  mod/workspace/templates/location_new.js
  mod/workspace/templates/location_update.js
  mod/workspace/templates/locations_delete.js
  mod/workspace/templates/mvt.js
  mod/workspace/templates/mvt_geom.js
  mod/workspace/templates/wkt.js
  tests/mod/query.test.mjs
Labels: Feature, Security, v4.13.0

#1647 Spread this.location.layer
  lib/ui/Dataview.mjs
Labels: Bug, v4.12.2

#1640 Replace bcrypt node module with utils module
  README.md
  mod/user/fromACL.js
  mod/user/register.js
  mod/utils/bcrypt.js
  package.json
Labels: Code, Security

#1674 Fix Ol Version Check
  lib/mapp.mjs
  lib/utils/_utils.mjs
  lib/utils/olScript.mjs
  tests/browser/local.test.mjs
  tests/lib/mapp.test.mjs
Labels: Bug, Code, v4.12.3

#1681 Template fields fieldsmap
  mod/query.js
  mod/workspace/templates/cluster.js
  mod/workspace/templates/cluster_hex.js
  mod/workspace/templates/geojson.js
  mod/workspace/templates/location_get.js
  mod/workspace/templates/mvt.js
  mod/workspace/templates/wkt.js
  tests/assets/layers/scratch/layer_fields.json
  tests/browser/local.test.mjs
  tests/mod/workspace/templates/_templates.test.mjs
  tests/mod/workspace/templates/cluster.test.mjs
  tests/mod/workspace/templates/cluster_hex.test.mjs
  tests/mod/workspace/templates/geojson.test.mjs
  tests/mod/workspace/templates/location_get.test.mjs
  tests/mod/workspace/templates/mvt.test.mjs
  tests/mod/workspace/templates/wkt.test.mjs
  tests/workspace.json
Labels: Code, Security

#1682 Esbuild, Chrome Debugging & Live reload
  .gitignore
  DEVELOPING.md
  esbuild.config.mjs
  lib/mapp.mjs
  nodemon.json
  package.json
Labels: Documentation

#1680 Fix svgTemplates reference in mapview
  lib/mapview/_mapview.mjs
  public/tests/_base.test.mjs
  public/views/_default.html
  tests/lib/utils/svgTemplates.test.mjs
  tests/workspace.json
Labels: Bug, v4.12.3

#1675 Filter Panel: Location match amount display
  lib/ui/layers/_layers.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/utils/_utils.mjs
  lib/ui/utils/locationCount.mjs
  public/css/_drawer.css
  public/css/ui.css
Labels: Feature, UI, v4.13.0

#1700 Helpdialog - Minimize and Close Buttons
  lib/ui/elements/helpDialog.mjs
Labels: v4.12.3

#1702 Update Cloudfront Provider to Support Node.js Native Fetch API Buffer Handling
  mod/provider/cloudfront.js
Labels: Bug, v4.12.3

#1708 Roles should be stripped from layer JSON
  mod/utils/roles.js
  mod/workspace/_workspace.js
Labels: Bug, Code

#1705 Layer View: Layer / Layer Group distinction
  public/css/_layerview.css
  public/css/ui.css
Labels: CSS, UI, v4.12.3

#1713 Shortcircuit keyvalue_dictionary parseObject on mapview key
  lib/location/_location.mjs
  lib/plugins/keyvalue_dictionary.mjs
  tests/assets/plugins/assignMapview.js
  tests/plugins/_plugins.test.mjs
  tests/workspace.json
Labels: Bug, Documentation

#1698 API Sign: Change the S3 Provider into a signer
  mod/provider/_provider.js
  mod/provider/s3.js
  mod/sign/_sign.js
  mod/sign/s3.js
  package.json
Labels: Feature, Code, v4.13.0

#1707 Test bundle, Documentation & Codi 🐶 Update
  .gitignore
  DEVELOPING.md
  TESTING.md
  esbuild.config.mjs
  eslint.config.mjs
  nodemon.json
  package.json
  public/tests/layer.test.mjs
  public/views/_test.html
  tests/_mapp.test.mjs
  tests/assets/layers/cluster/layer.json
  tests/assets/layers/wkt/infoj.json
  tests/assets/layers/wkt/layer.json
  tests/assets/layers/wkt/style.json
  tests/browser/local.test.mjs
  tests/lib/dictionaries/baseDictionary.test.mjs
  tests/lib/dictionaries/keyValueDictionary.test.mjs
  tests/lib/dictionaries/unknownLanguageTest.test.mjs
  tests/lib/layer/decorate.test.mjs
  tests/lib/layer/fade.test.mjs
  tests/lib/layer/format/mvt.test.mjs
  tests/lib/layer/format/vector.test.mjs
  tests/lib/location/create.test.mjs
  tests/lib/mapview/_mapview.test.mjs
  tests/lib/mapview/allfeatures.test.mjs
  tests/lib/mapview/attribution.test.mjs
  tests/lib/mapview/fitView.test.mjs
  tests/lib/mapview/geojson.test.mjs
  tests/lib/mapview/geometry.test.mjs
  tests/lib/mapview/getBounds.test.mjs
  tests/lib/mapview/infotip.test.mjs
  tests/lib/mapview/locate.test.mjs
  tests/lib/mapview/olcontrols.test.mjs
  tests/lib/mapview/popup.test.mjs
  tests/lib/ui/Tabview.test.mjs
  tests/lib/ui/layers/view.test.mjs
  tests/lib/ui/locations/entries/layer.test.mjs
  tests/lib/utils/numericFormatter.test.mjs
  tests/lib/utils/queryParams.test.mjs
  tests/utils/view.js
Labels: Testing, Documentation

#1724 mapview.addLayer merge/clone issue
  lib/mapview/addLayer.mjs
  tests/lib/mapview/addLayer.test.mjs
Labels: Bug

#1728 Template bug
  mod/query.js
  tests/mod/workspace/getTemplate.test.mjs
Labels: Bug, Code

#1723 mapview.interactions.Click
  lib/mapview/interactions/highlight.mjs
Labels: Feature, v4.12.4

#1736 Layer May Not Have Params.Fields
  lib/layer/format/vector.mjs
Labels: Bug, v4.12.4

#1714 Add layer.featureFormat option
  lib/layer/format/vector.mjs
  tests/assets/data/uk.json
  tests/assets/layers/geojson/layer.json
  tests/lib/layer/format/vector.test.mjs
Labels: Feature

#1743 fix merge template object issue
  mod/workspace/mergeTemplates.js
Labels: Bug, v4.12.4

#1740 Dataview Entry: Hide/Show toolbar along with location dataview
  lib/ui/Dataview.mjs
  tests/assets/layers/location_mock/infoj.json
  tests/browser/local.test.mjs
  tests/lib/ui/Dataview.test.mjs
  tests/lib/ui/_ui.test.mjs
Labels: Bug, UI, v4.12.4

#1752 Updated Filter Wording [en]
  lib/ui/layers/panels/filter.mjs
Labels: Code

#1749 Scrollbar rules in ui.css.
  public/css/_ui.css
  public/css/ui.css
Labels: CSS, v4.13.0

#1756 Assign array for featureLookup in layer entry
  lib/ui/locations/entries/layer.mjs
Labels: Bug

#1727 Signing API: Cloudfront Signer
  mod/provider/_provider.js
  mod/provider/cloudfront.js
  mod/sign/_sign.js
  mod/sign/cloudfront.js
  mod/sign/s3.js
  package.json
Labels: Feature, Code, v4.13.0

#1766 Fix geojson json build object string
  mod/query.js
  mod/workspace/templates/geojson.js
  tests/_mapp.test.mjs
  tests/browser/local.test.mjs
  tests/mod/workspace/templates/geojson.test.mjs
Labels: Bug

#1760 saml2 optional dependency.
  mod/user/saml.js
Labels: Code

#1762 Tabview BtnRow must be set to display block in the `activate`
  lib/ui/Tabview.mjs
Labels: Bug

#1753 get location from feature
  lib/layer/decorate.mjs
  lib/location/get.mjs
  lib/mapview/addLayer.mjs
  lib/ui/layers/listview.mjs
  lib/ui/locations/listview.mjs
  lib/ui/locations/view.mjs
  public/tests/_base.test.mjs
  public/views/_default.html
  tests/assets/data/uk.json
  tests/assets/layers/geojson/layer.json
  tests/lib/layer/decorate.test.mjs
  tests/lib/layer/format/vector.test.mjs
  tests/lib/ui/layers/panels/filter.test.mjs
Labels: Feature, Code

#1765 JSON Toolbar Method
  lib/ui/utils/jsonDataview.mjs
  lib/utils/_utils.mjs
  lib/utils/textFile.mjs
  tests/assets/dataviews/dataviews_json.json
Labels: Feature, Plugin
