Repository GEOLYTIX/xyz, pull requests merged in 2024-02, with the labels that each got.

#1100 Review ui.elements.modal
  lib/ui/elements/modal.mjs
  lib/ui/layers/panels/style.mjs
  public/css/_ui.css
  public/css/ui.css
Labels: Feature

#1105 Cut SQL array from location_get request params
  mod/query.js
  mod/workspace/templates/location_get.js
Labels: Bug

#1107 preserveDrawingBuffer defaults true for maplibre layer
  lib/layer/format/maplibre.mjs
Labels: Bug, Code

#1109 Remove locale dataset from default view.
  public/views/_default.html
Labels: Security

#1114 Lock the remote address for 30 seconds on post requests.
  mod/user/register.js
Labels: Security

#1118 Set newValue to current date/time if value is null
  lib/ui/locations/entries/date.mjs
Labels: Feature

#1106 Do not reset candidateKeys in highlight interaction clear event.
  lib/mapview/interactions/highlight.mjs
Labels: Bug

#1116 Store user session token in process
  mod/user/auth.js
  mod/user/fromACL.js
Labels: Security

#1119 Err on null password login
  mod/user/fromACL.js
Labels: Security

#1120 Querying a layer with role restrictions crashes the process.
  mod/query.js
Labels: Bug

#1121 Layer filter legend render
  lib/ui/elements/legendIcon.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/legends/basic.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/distributed.mjs
  lib/ui/layers/legends/graduated.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/layers/panels/style.mjs
Labels: Bug

#1123 Filter toolbar elements to remove undefined
  lib/ui/Dataview.mjs
Labels: Bug

#1125 Review Location view module; edit toggle & confirmation dialogs.
  lib/location/decorate.mjs
  lib/ui/locations/view.mjs
Labels: Bug, Code

#1131 headerFilter Map Issue
  lib/ui/utils/tabulator.mjs
Labels: Bug

#1133 Role Check Fix
  mod/workspace/_workspace.js
Labels: Bug

#1130 Do not logout on failure to retrieve locales or locale
  public/css/_ui.css
  public/css/ui.css
  public/views/_default.js
Labels: Bug

#1140 vector / mvt layer with tables zoom restriction
  lib/layer/decorate.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/mapview/_mapview.mjs
  lib/ui/layers/view.mjs
Labels: Bug

#1142 clear highlight [candidates] on mouseleave and mousemove.
  lib/mapview/interactions/highlight.mjs
Labels: Bug

#1145 Load sync plugins in sync before async plugins
  lib/mapview/_mapview.mjs
  lib/plugins.mjs
  public/views/_default.js
Labels: Feature

#1135 update user in cookie
  mod/user/cookie.js
  public/views/_default.html
  public/views/_default.js
Labels: Feature, Code, Security

#1137 Set language in user verification
  mod/user/register.js
  mod/user/verify.js
Labels: Feature, Security

#1147 Fix Numeric and Date Inputs
  lib/ui/utils/tabulator.mjs
Labels: Bug

#1148 ol 8.2
  .gitignore
  lib/layer/featureFormats.mjs
  lib/mapview/geoJSON.mjs
  lib/utils/_utils.mjs
  public/views/_default.html
Labels: Bug

#1149 Allow hiding of Hovers and Labels
  lib/ui/layers/panels/style.mjs
Labels: Feature

#1150 maplibre v4.0.2 bump and esm load
  lib/layer/format/maplibre.mjs
Labels: Code

#1151 Add check for Style labelCheckbox
  lib/ui/layers/panels/style.mjs
Labels: Bug

#1158 The hover method must be assigned if not member of the hover object.
  lib/ui/layers/panels/style.mjs
Labels: Bug

#1157 Assign ID for wkt_properties features
  lib/layer/featureFormats.mjs
Labels: Bug

#1153 Use script module for default view
  public/views/_default.html
  public/views/_default.js
Labels: Code

#1152 promise renderComplete from addLayer
  lib/mapview/addLayer.mjs
Labels: Feature

#1156 OL9 support & googleMapTiles format
  lib/layer/format/_format.mjs
  lib/layer/format/googleMapTiles.mjs
  lib/utils/_utils.mjs
  public/views/_default.html
Labels: Feature

#1155 Remove not from if to remove
  lib/ui/elements/dropdown.mjs
  lib/ui/layers/panels/filter.mjs
Labels: Bug

#1160 Jsdoc Favicon and Title Updates ✍️
  jsdoc_mapp.json
  jsdoc_xyz.json
Labels: Code
