Repository GEOLYTIX/xyz, pull requests merged in 2024-10, with the labels that each got.

#1510 Update sqlFilter mod
  README.md
  mod/query.js
  mod/utils/sqlFilter.js
  tests/mod/utils/sqlFilter.test.mjs
Labels: Security, v4.11.0

#1515 Fix code scanning alert no. 191: Type confusion through parameter tampering
  mod/query.js
Labels: Code, Testing

#1516 Fix code scanning alert no. 204: Prototype-polluting function
  lib/utils/merge.mjs
Labels: Code, Testing

#1518 add SQL and filter property
  mod/query.js
Labels: Testing, Documentation

#1526 Prevent Crash when role access denied on /workspace/test
  mod/workspace/_workspace.js
Labels: Bug, Testing

#1523 Query Templates: Location count template
  mod/workspace/templates/_queries.js
  mod/workspace/templates/location_count.js
Labels: Feature, v4.12.0

#1512 Testing execution update
  tests/browser/local.test.mjs
  tests/lib/dictionaries/baseDictionary.test.mjs
  tests/lib/dictionaries/keyValueDictionary.test.mjs
  tests/lib/dictionaries/unknownLanguageTest.test.mjs
  tests/lib/layer/changeEnd.test.mjs
  tests/lib/layer/decorate.test.mjs
  tests/lib/layer/fade.test.mjs
  tests/lib/layer/format/vector.test.mjs
  tests/lib/ui/locations/infoj.test.mjs
  tests/mod/workspace/_workspace.test.mjs
  tests/plugins/link_button.test.mjs
Labels: Testing, v4.12.0

#1521 CSS For Infoj Headers Update
  public/css/_locationview.css
  public/css/ui.css
Labels: CSS, v4.12.0

#1536 readme update
  README.md
Labels: Documentation

#1529 Update Layer Test
  public/tests/integrity.test.mjs
  public/tests/layer.test.mjs
  public/tests/workspace.test.mjs
Labels: Bug, Testing

#1527 Update queryParams documentation
  lib/ui/Dataview.mjs
  lib/ui/locations/entries/query_button.mjs
  lib/ui/locations/entries/vector_layer.mjs
  lib/ui/locations/infoj.mjs
  lib/utils/paramString.mjs
  lib/utils/queryParams.mjs
  tests/browser/local.test.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/paramString.test.mjs
  tests/lib/utils/queryParams.test.mjs
Labels: Documentation

#1525 Allow for layer reload callback from applyFilter
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/ui/layers/filters.mjs
  tests/lib/ui/layers/filters.test.mjs
Labels: Feature, v4.12.0

#1538 Dialog: Show function and related tests
  lib/ui/elements/dialog.mjs
  tests/lib/ui/elements/dialog.test.mjs
Labels: Code, Testing, Documentation, v4.12.0

#1535 Destroy redirect cookie
  mod/user/cookie.js
  mod/user/login.js
  public/views/login/_login_en.html
Labels: Bug, Security, v4.12.0

#1541 Dialog: minimize/maximize functionality
  lib/ui/elements/alert.mjs
  lib/ui/elements/confirm.mjs
  lib/ui/elements/dialog.mjs
  public/css/_dialog.css
  public/css/_ui.css
  public/css/ui.css
  public/icons/icon-close.svg
  tests/lib/ui/elements/alert.test.mjs
  tests/lib/ui/elements/confirm.test.mjs
  tests/lib/ui/elements/dialog.test.mjs
Labels: Code, Testing, Documentation, v4.12.0

#1539 Remove filter method in filter dropdown
  lib/ui/elements/card.mjs
  lib/ui/elements/dropdown.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
  tests/lib/ui/layers/_layers.test.mjs
  tests/lib/ui/layers/filters.test.mjs
  tests/lib/ui/layers/panels/filter.test.mjs
  tests/lib/utils/queryParams.test.mjs
  tests/workspace.json
Labels: Code, Documentation, UI, v4.12.0

#1467 mapviewPromise method for async mapview decoration; svg_templates util
  lib/mapview/_mapview.mjs
  lib/plugins/svg_templates.mjs
  lib/utils/_utils.mjs
  lib/utils/svgTemplates.mjs
  public/tests/_base.test.mjs
  public/views/_default.html
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/svgTemplates.test.mjs
Labels: Feature, Code, v4.12.0

#1549 Remove streetview
  lib/utils/gazetteer.mjs
  public/css/_dialog.css
  public/css/_locationview.css
  public/css/ui.css
Labels: Code

#1552 Input Elements: CSS changes
  lib/ui/elements/numericInput.mjs
  lib/ui/elements/slider_ab.mjs
  public/css/_colours.css
  public/css/_dialog.css
  public/css/_inputs.css
  public/css/ui.css
Labels: UI, v4.12.0

#1558 callback on invalid numericInput
  lib/ui/elements/numericInput.mjs
Labels: Bug, v4.12.0

#1561 Polish dictionary entries in drawing module.
  lib/ui/elements/drawing.mjs
Labels: Code, v4.12.0

#1565 versioncheck util
  lib/utils/_utils.mjs
  lib/utils/versionCheck.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/versionCheck.mjs
Labels: Feature, v4.x.x

#1570 Nullish Assign syncPlugins
  lib/mapview/_mapview.mjs
Labels: Bug, v4.12.0

#1568 Move Icon Scaling to the bottom instead of before themes
  lib/ui/layers/panels/style.mjs
Labels: UI, v4.12.0

#1567 Filter panel: reset all function
  lib/ui/elements/card.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
  public/css/_button.css
  public/css/ui.css
  tests/lib/ui/layers/panels/filter.test.mjs
Labels: Feature, Documentation, UI, v4.12.0

#1563 Mobile View Fixes
  lib/mapview/interactions/highlight.mjs
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/locations/entries/dataview.mjs
  lib/utils/_utils.mjs
  lib/utils/mobile.mjs
  public/css/_mapp.css
  public/css/mapp.css
  public/css/ui.css
  public/views/_default.html
Labels: Bug, v4.12.0

#1564 query params from template, layer, locale, or workspace
  lib/layer/decorate.mjs
  lib/layer/featureHover.mjs
  lib/ui/layers/filters.mjs
  lib/ui/locations/entries/text.mjs
  lib/utils/queryParams.mjs
  mod/query.js
  mod/workspace/getLayer.js
  mod/workspace/mergeTemplates.js
  tests/mod/query.test.mjs
  tests/workspace.json
Labels: Bug, Code, Security, v4.12.0

#1575 bump ol to 10.2.1
  lib/mapp.mjs
  public/views/_default.html
  public/views/_test.html
Labels: Code, v4.12.0

#1579 Maplibre v4.7.1
  lib/layer/format/maplibre.mjs
Labels: v4.12.0

#1577 Infoj Entry - Layer Dependents
  lib/location/decorate.mjs
  tests/assets/layers/scratch/infoj.json
  tests/workspace.json
Labels: Feature, v4.12.0

#1583 Theme filter and layer.featureFilter to filter features in style.
  lib/layer/_layer.mjs
  lib/layer/changeEnd.mjs
  lib/layer/featureFilter.mjs
  lib/layer/featureStyle.mjs
  lib/layer/themes/categorized.mjs
  lib/ui/layers/legends/categorized.mjs
  tests/lib/layer/_layer.test.mjs
  tests/lib/layer/featureFilter.test.mjs
Labels: Feature, Code, Testing, Documentation, v4.12.0

#1590 sqlFilter export
  mod/utils/sqlFilter.js
Labels: Bug, v4.12.0

#1592 Update version docs
  DEVELOPING.md
  lib/mapp.mjs
  version.js
Labels: Documentation, v4.12.0

#1386 entry type:layer to replace mvt_clone
  lib/layer/_layer.mjs
  lib/layer/featureHover.mjs
  lib/layer/featureStyle.mjs
  lib/layer/format/mvt.mjs
  lib/location/get.mjs
  lib/mapview/addLayer.mjs
  lib/ui/elements/layerStyle.mjs
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/defaults.mjs
  lib/ui/locations/entries/layer.mjs
  lib/ui/locations/entries/mvt_clone.mjs
  tests/assets/layers/mvt/layer.json
  tests/lib/ui/locations/entries/_entries.test.mjs
  tests/lib/ui/locations/entries/layer.test.mjs
  tests/workspace.json
Labels: Bug, Feature, v4.12.0

#1596 Warn on feature properties properties
  lib/layer/featureStyle.mjs
Labels: Code, Testing

#1600 Dialog element should not have #fff background colour.
  public/css/_dialog.css
  public/css/ui.css
Labels: CSS, UI

#1606 Remove commented featureSet script
  lib/layer/featureStyle.mjs
Labels: Code

#1605 Spread properties into wkt features
  lib/layer/featureFormats.mjs
Labels: Bug

#1598 /ui/locations/entries/pin default_icon without a location.record property
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/pin.mjs
  lib/ui/locations/listview.mjs
Labels: Bug, v4.12.0

#1604 Header links not working on deployed documentation
  api/README.md
  express.js
  jsdoc_mapp.json
  jsdoc_xyz.json
  lib/README.md
  lib/mapp.mjs
Labels: Bug, Documentation, v4.12.1

#1612 Fix feature properties
  lib/layer/featureFormats.mjs
  lib/layer/format/vector.mjs
  lib/layer/themes/graduated.mjs
  lib/location/nnearest.mjs
  lib/mapview/interactions/highlight.mjs
  lib/plugins/feature_info.mjs
  lib/utils/olStyle.mjs
  tests/lib/ui/locations/entries/pin.test.mjs
Labels: Bug, v4.12.1

#1616 Deprecate mongodb provider
  mod/provider/getFrom.js
  mod/provider/mongodb.js
Labels: Deprecated

#1615 Dialog CSS/ Attribution link css: add z-index to dialogand remove from attribution links
  DEVELOPING.md
  public/css/_dialog.css
  public/css/_inputs.css
  public/css/_mapp.css
  public/css/mapp.css
  public/css/ui.css
Labels: Bug, CSS, v4.12.1

#1622 Geojson featureFormat property spread
  lib/layer/featureFormats.mjs
  tests/lib/layer/featureFormats.test.mjs
Labels: Bug, v4.12.1

#1617 deprecate mbtiles format
  lib/layer/format/_format.mjs
  lib/layer/format/mbtiles.mjs
Labels: v4.13.0, Deprecated

#1601 remove mapp.layer changeend method
  lib/layer/_layer.mjs
  lib/layer/changeEnd.mjs
  lib/layer/decorate.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
  lib/location/create.mjs
  lib/mapview/_mapview.mjs
  lib/plugins/zoomBtn.mjs
  lib/ui/Dataview.mjs
  lib/ui/elements/layerStyle.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/view.mjs
  lib/ui/locations/entries/layer.mjs
  tests/lib/layer/_layer.test.mjs
  tests/lib/ui/layers/_layers.test.mjs
  tests/lib/ui/layers/view.test.mjs
  tests/lib/utils/queryParams.test.mjs
Labels: Bug, Code, Documentation, v4.12.1

#1542 remove cloudinary provider module
  express.js
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/utils/imagePreview.mjs
  mod/provider/_provider.js
  mod/provider/cloudinary.js
  mod/sign/_sign.js
  mod/sign/cloudinary.js
  public/css/_locationview.css
  public/css/ui.css
  tests/lib/ui/locations/entries/_entries.test.mjs
  tests/lib/ui/locations/entries/cloudinary.test.mjs
Labels: Code, Plugin, Documentation, v4.13.0

#1628 Explain the WORKSPACE AGE in more detail
  mod/workspace/_workspace.js
  mod/workspace/cache.js
  mod/workspace/getTemplate.js
Labels: Documentation
