Repository GEOLYTIX/xyz, pull requests merged in 2024-03, with the labels that each got.

#1164 Clear all filters fix - needs the second check
  lib/ui/layers/panels/filter.mjs
Labels: Bug

#1166 Replace zoom draw style function with expression.
  lib/mapview/interactions/zoom.mjs
Labels: Bug

#1162 Numeric filter format
  lib/ui/elements/_elements.mjs
  lib/ui/elements/numericFormatter.mjs
  lib/ui/elements/slider_ab.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/utils/tabulator.mjs
Labels: Feature

#1168 User Key and Query docs
  mod/query.js
  mod/user/key.js
Labels: Documentation

#1169 Null Geometries not being displayed when dependents used
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1170 Graduated zeroes error
  lib/layer/themes/graduated.mjs
Labels: Bug

#1173 ACL No User Present and Verification bugs
  jsdoc_mapp.json
  jsdoc_xyz.json
  mod/user/fromACL.js
  mod/user/verify.js
  public/views/_user.html
Labels: Bug, Documentation

#1174 Use password_reset for registration
  mod/user/_user.js
  mod/user/delete.js
  mod/user/fromACL.js
  mod/user/list.js
  mod/user/register.js
  mod/user/update.js
  mod/user/verify.js
  mod/utils/reqHost.js
  public/views/_user.html
Labels: Bug

#1176 Fixes for infoj entry and filter issues
  lib/ui/elements/numericFormatter.mjs
  lib/ui/layers/filters.mjs
  lib/ui/locations/entries/numeric.mjs
  lib/ui/utils/tabulator.mjs
Labels: Bug

#1177 ACL List changes
  mod/user/list.js
Labels: Code, Documentation

#1178 Formatting fix
  lib/ui/elements/numericFormatter.mjs
  lib/ui/locations/entries/numeric.mjs
Labels: Bug

#1180 bump crypto libraries
  README.md
  mod/user/fromACL.js
  mod/user/register.js
  package.json
Labels: Security

#1171 Fix issue snapping to mvt
  lib/layer/format/mvt.mjs
  lib/mapview/interactions/snap.mjs
Labels: Bug

#1182 Check whether format exists in layer decorator
  lib/layer/decorate.mjs
Labels: Bug

#1184 Create layer changend module.
  lib/layer/_layer.mjs
  lib/layer/changeEnd.mjs
  lib/layer/decorate.mjs
  lib/layer/format/mvt.mjs
  lib/layer/format/vector.mjs
Labels: Bug, Code

#1186 Assign params as URL paramstring to tile layer URI
  lib/layer/format/tiles.mjs
  lib/utils/paramString.mjs
Labels: Feature

#1187 Split plugins into modules; Add keyvalue_dictionary
  lib/mapp.mjs
  lib/plugins.mjs
  lib/plugins/_plugins.mjs
  lib/plugins/admin.mjs
  lib/plugins/fullscreen.mjs
  lib/plugins/keyvalue_dictionary.mjs
  lib/plugins/locator.mjs
  lib/plugins/login.mjs
  lib/plugins/svg_templates.mjs
  lib/plugins/zoomBtn.mjs
  lib/plugins/zoomToArea.mjs
Labels: Code

#1189 Add console.log for chart and tabulator imports
  lib/ui/utils/Chart.mjs
  lib/ui/utils/tabulator.mjs
Labels: Code

#1188 Provide buffer param for cloudfront provider
  mod/provider/cloudfront.js
Labels: Feature

#1191 The request params object may be optional
  mod/provider/cloudfront.js
Labels: Bug

#1190 Codi 🐶
  .github/workflows/unit_tests.yml
  package.json
  tests/mod/utils/merge.test.mjs
  tests/mod/utils/roles.test.mjs
Labels: Testing

#1194 Throw error for invalid query parameter substitution
  mod/query.js
Labels: Bug

#1185 Role merge
  lib/layer/decorate.mjs
  mod/query.js
  mod/utils/roles.js
  mod/workspace/_workspace.js
  mod/workspace/getLayer.js
  package.json
  tests/mod/utils/merge.test.mjs
  tests/mod/utils/roles.test.js
  tests/mod/utils/roles.test.mjs
Labels: Feature, Code

#1192 Remove empty cat filter from theme legend
  lib/ui/layers/legends/categorized.mjs
Labels: Bug

#1195 Codi 🐶 default base test
  lib/mapview/_mapview.mjs
  mod/workspace/templates/_views.js
  public/tests/_default.test.mjs
  public/views/_test.html
Labels: Testing

#1197 Remove the API /location path from express routes.
  express.js
Labels: Code

#1196 🐶 Add Layer Test Suite 🧪
  mod/workspace/templates/get_last_location.js
  public/tests/Sure! Here's an updated write-up with em.md
  public/tests/_default.test.mjs
  public/tests/layer.test.mjs
Labels: Testing

#1198 Provide label and names for input elements
  lib/ui/Gazetteer.mjs
  lib/ui/elements/chkbox.mjs
  lib/ui/elements/slider.mjs
Labels: Code
