Repository GEOLYTIX/xyz, pull requests merged in 2025-06, with the labels that each got.

#2189 (fix csv_upload): Csv upload schema fix
  lib/utils/csvUpload.mjs
Labels: Bug

#2194 fix (select input): Select CSS
  public/css/base/_globals.css
  public/css/base/_inputs.css
  public/css/elements/_dropdown.css
  public/css/ui.css
Labels: CSS

#2176 feature(roles): Return roles.tree from workspace, support roles with dot separator.
  mod/utils/roles.js
  mod/workspace/_workspace.js
  tests/mod/utils/roles.test.mjs
Labels: Feature, Code

#2208 Disable geometry entry if api method fails to assign a value.
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#2209 fix(layer.entries) - Queryparams from layer and locale must be assigned to entry
  lib/ui/locations/entries/layer.mjs
Labels: Bug

#2200 fix(vector): Cluster source change event method fails with empty features
  lib/layer/featureFormats.mjs
  lib/layer/featureStyle.mjs
  lib/layer/format/vector.mjs
Labels: Bug

#2211 package(biome): v2 update
  .github/workflows/biome.yml
  package.json
  public/css/base/_material_icons.css
  public/views/_default.html
  public/views/_user.html
  public/views/login/_login.css
  public/views/login/_login_de.html
  public/views/login/_login_en.html
  public/views/login/_login_fr.html
  public/views/login/_login_ja.html
  public/views/login/_login_ko.html
  public/views/login/_login_pl.html
  public/views/login/_login_zh.html
  public/views/register/_register.css
  public/views/register/_register_de.html
  public/views/register/_register_en.html
  public/views/register/_register_fr.html
  public/views/register/_register_ja.html
  public/views/register/_register_ko.html
  public/views/register/_register_pl.html
  public/views/register/_register_zh.html
Labels: Code

#2203 feat(util): scriptElement utils module and mapboxStyle format
  lib/layer/format/mapboxStyle.mjs
  lib/utils/_utils.mjs
  lib/utils/scriptElement.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/scriptElement.test.mjs
Labels: Bug, Feature

#2216 security(api): remove user controlled data
  api/api.js
Labels: Security

#2220 Load mapbox rtl plugin from jsdelivr cdn
  lib/layer/format/maplibre.mjs
  public/js/mapbox-gl-rtl-text.js
Labels: Code

#2222 Basic theme legend: Show in the legend
  lib/ui/elements/legendIcon.mjs
  lib/ui/layers/legends/basic.mjs
  public/css/layout/_legend.css
  public/css/mapp.css
  tests/browser/local.test.mjs
  tests/lib/ui/layers/_layers.test.mjs
  tests/lib/ui/layers/legends/basic.test.mjs
Labels: Bug
