Repository GEOLYTIX/xyz, pull requests merged in 2025-09, with the labels that each got.

#2356 Specify the lang property for the user admin view template
  public/views/_user.html
Labels: Bug

#2360 Prevent the use of nested template
  lib/ui/locations/entries/textarea.mjs
  lib/ui/locations/entries/time.mjs
Labels: Code, Documentation

#2358 Unexpected duplicate selector "body" in mapp and ui css
  public/css/_mapp.css
  public/css/_ui.css
  public/css/base/_body.css
  public/css/base/_colours.css
  public/css/base/_common.css
  public/css/base/_globals.css
  public/css/layout/_divider.css
  public/css/layout/_map_attribution.css
  public/css/mapp.css
  public/css/ui.css
  public/views/_default.html
Labels: Code, CSS

#2366 /mod/user/register nested template literals and languageTemplate calls.
  mod/user/register.js
Labels: Security

#2379 fix(layerStyle): Else Return Preventing Slider Creation
  lib/ui/elements/layerStyle.mjs
Labels: Bug

#2390 _user mod error message content type
  mod/user/_user.js
Labels: Security

#2397 Remove deprecated Style method
  lib/layer/_layer.mjs
Labels: Code, Deprecated

#2398 Remove deprecated ui.utils
  lib/ui/utils/_utils.mjs
Labels: Code

#2383 Enable caching of cloudfront templates
  mod/provider/_provider.js
  mod/provider/cloudfront.js
  mod/provider/getFrom.js
  mod/sign/cloudfront.js
  mod/sign/cloudinary.js
  mod/workspace/_workspace.js
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
  mod/workspace/getTemplate.js
  mod/workspace/mergeTemplates.js
  tests/mod/provider/cloudfront.test.mjs
Labels: Bug, Code

#2414 feat(query): Show missing params
  mod/query.js
Labels: Feature, Code

#2375 fix(login/register): language templates and forms
  lib/mapp.mjs
  lib/ui.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/chkbox.mjs
  lib/ui/elements/loginForm.mjs
  lib/ui/elements/registerForm.mjs
  mod/workspace/templates/_mails.js
  mod/workspace/templates/_msgs.js
  mod/workspace/templates/_views.js
  public/css/_ui.css
  public/css/base/_inputs.css
  public/css/elements/_login_form.css
  public/css/ui.css
  public/dictionaries/de.json
  public/dictionaries/en.mjs
  public/dictionaries/es.json
  public/dictionaries/fr.json
  public/dictionaries/it.json
  public/dictionaries/ja.json
  public/dictionaries/ko.json
  public/dictionaries/pl.json
  public/dictionaries/th.json
  public/dictionaries/tr.json
  public/dictionaries/zh.json
  public/dictionaries/zh_tw.json
  public/views/_login.html
  public/views/login/_login.css
  public/views/login/_login.js
  public/views/login/_login_de.html
  public/views/login/_login_en.html
  public/views/login/_login_fr.html
  public/views/login/_login_ja.html
  public/views/login/_login_ko.html
  public/views/login/_login_pl.html
  public/views/login/_login_zh.html
  public/views/register/_register.css
  public/views/register/_register.js
  public/views/register/_register_de.html
  public/views/register/_register_en.html
  public/views/register/_register_fr.html
  public/views/register/_register_ja.html
  public/views/register/_register_ko.html
  public/views/register/_register_pl.html
  public/views/register/_register_zh.html
Labels: Bug, Feature, Code, CSS
