Repository GEOLYTIX/xyz, pull requests merged in 2025-03, with the labels that each got.

#1915 Allow to set datetime default
  lib/ui/locations/entries/date.mjs
  lib/utils/temporal.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/temporal.test.mjs
Labels: Bug

#1957 Locale without layers should not crash the process
  mod/workspace/getLocale.js
Labels: Bug

#1987 Remove fetch api
  api/api.js
  express.js
  mod/fetch.js
Labels: Code, Deprecated

#1975 Fix for dark mode - media queries for toolbar on mobile;
  public/css/base/_dark_mode.css
  public/css/ui.css
Labels: CSS

#1972 Check mapbox style and accessToken
  lib/layer/format/maplibre.mjs
Labels: Bug

#1988 update default user admin view
  public/views/_user.html
Labels: Code

#1999 _default view - restored search icon when location tab is inactive;
  public/views/_default.html
Labels: CSS

#2003 Map toolbar button text - css alignment
  public/css/_button.css
  public/css/layout/_toolbars.css
  public/css/ui.css
Labels: CSS

#2010 node-saml v5.0.1 bump
  package.json
Labels: Bug, Security

#2013 Conditional field template lookup in query module
  mod/query.js
Labels: Bug

#2018 Calling API with parameters in square brackets
  api/api.js
Labels: Bug

#2025 Featurehover table check
  lib/layer/featureHover.mjs
Labels: Bug
