Repository GEOLYTIX/xyz, pull requests merged in 2025-08, with the labels that each got.

#2306 Apply val-changed style to select-dropdown class element.
  public/css/base/_common.css
  public/css/ui.css
Labels: Bug

#2304 Replace unpkg references with jsdelivr
  lib/layer/format/mapboxStyle.mjs
  public/views/_user.html
  tests/lib/utils/scriptElement.test.mjs
Labels: Code

#2309 hideDisabled layer.view
  lib/ui/layers/view.mjs
Labels: Feature

#2307 filter.viewport for numeric filter with slider and histogram
  lib/ui/elements/slider_ab.mjs
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/utils/histogram.mjs
  mod/workspace/templates/field_minmax.js
  public/css/elements/_slider.css
  public/css/ui.css
Labels: Feature, Code

#2317 fix(dataview): Dynamic dataviews data is not refreshed when data exists
  lib/ui/Tabview.mjs
Labels: Bug

#2313 pnpm Package Manager 📦
  .github/workflows/deploy-docs.yml
  .github/workflows/unit_tests.yml
  .gitignore
  DEVELOPING.md
  DOCUMENTATION.md
  TESTING.md
  package.json
  version.js
Labels: Code

#2333 locale / layer queryparams must be assigned in the queryParams module
  lib/utils/queryParams.mjs
  mod/query.js
Labels: Bug

#2334 Fix issue vector layer srid issues
  lib/layer/featureFormats.mjs
  lib/layer/format/vector.mjs
Labels: Bug

#2341 fix(icons): Add notranslate class to material-symbols-outlined class elements
  lib/plugins/admin.mjs
  lib/plugins/dark_mode.mjs
  lib/plugins/feature_info.mjs
  lib/plugins/fullscreen.mjs
  lib/plugins/link_button.mjs
  lib/plugins/locator.mjs
  lib/plugins/login.mjs
  lib/plugins/userIDB.mjs
  lib/plugins/zoomBtn.mjs
  lib/plugins/zoomToArea.mjs
  lib/ui/elements/btnPanel.mjs
  lib/ui/elements/card.mjs
  lib/ui/elements/chkbox.mjs
  lib/ui/elements/dialog.mjs
  lib/ui/elements/drawer.mjs
  lib/ui/elements/drawing.mjs
  lib/ui/elements/pills.mjs
  lib/ui/elements/toast.mjs
  lib/ui/elements/userLocale.mjs
  lib/ui/layers/listview.mjs
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/layers/panels/draw.mjs
  lib/ui/layers/panels/filter.mjs
  lib/ui/layers/panels/reports.mjs
  lib/ui/layers/panels/style.mjs
  lib/ui/layers/view.mjs
  lib/ui/locations/entries/boolean.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/link.mjs
  lib/ui/locations/entries/title.mjs
  lib/ui/locations/infoj.mjs
  lib/ui/locations/view.mjs
  lib/ui/utils/dataview.mjs
  lib/ui/utils/imagePreview.mjs
  public/views/_default.html
Labels: Bug

#2340 fix(filterDialog): unnest filterDialog method
  lib/ui/layers/panels/filter.mjs
Labels: Code, Documentation

#2343 fix(geometry): No Value layer removal
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#2347 Add neverBuiltDependencies to package.json
  package.json
Labels: Code
