Repository GEOLYTIX/xyz, pull requests merged in 2025-04, with the labels that each got.

#1960 Review colour schema and update dark_mode plugin
  lib/plugins/_plugins.mjs
  lib/plugins/dark_mode.mjs
  lib/ui/elements/pills.mjs
  lib/ui/utils/_utils.mjs
  lib/ui/utils/cssColourTheme.mjs
  public/css/_button.css
  public/css/_colours.css
  public/css/_dialog.css
  public/css/_icons.css
  public/css/_inputs.css
  public/css/_tabulator.scss
  public/css/_ui.css
  public/css/base/_button.css
  public/css/base/_colours.css
  public/css/base/_common.css
  public/css/base/_dark_mode.css
  public/css/base/_font.css
  public/css/base/_globals.css
  public/css/base/_icons.css
  public/css/base/_inputs.css
  public/css/base/_material_icons.css
  public/css/elements/_alert_confirm.css
  public/css/elements/_btnPanel.css
  public/css/elements/_dialog.css
  public/css/elements/_drawer.css
  public/css/elements/_dropdown.css
  public/css/elements/_key.css
  public/css/elements/_pills.css
  public/css/elements/_searchbox.css
  public/css/elements/_slider.css
  public/css/layout/_cloudinary.css
  public/css/layout/_divider.css
  public/css/layout/_infotip.css
  public/css/layout/_layerview.css
  public/css/layout/_locationview.css
  public/css/layout/_map_attribution.css
  public/css/layout/_ol.css
  public/css/layout/_popup.css
  public/css/layout/_scrollbar.css
  public/css/layout/_tabview.css
  public/css/layout/_toolbars.css
  public/css/mapp.css
  public/css/ui.css
  public/views/_default.html
Labels: Code, CSS, UI

#2048 CSS colour classes - cleanup;
  lib/plugins/login.mjs
  lib/ui/elements/card.mjs
  lib/ui/layers/view.mjs
  lib/ui/locations/entries/cloudinary.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/view.mjs
  public/css/base/_colours.css
  public/css/base/_inputs.css
  public/css/base/_material_icons.css
  public/css/mapp.css
  public/css/ui.css
Labels: Code, CSS

#2041 Insert template
  lib/ui/utils/jsonDataview.mjs
  lib/utils/csvUpload.mjs
  mod/workspace/templates/_queries.js
  mod/workspace/templates/sql_table_insert.js
  tests/mod/workspace/templates/_templates.test.mjs
  tests/mod/workspace/templates/cluster.test.mjs
  tests/mod/workspace/templates/cluster_hex.test.mjs
  tests/mod/workspace/templates/geojson.test.mjs
  tests/mod/workspace/templates/location_get.test.mjs
  tests/mod/workspace/templates/mvt.test.mjs
  tests/mod/workspace/templates/sql_table_insert.test.mjs
  tests/mod/workspace/templates/wkt.test.mjs
Labels: Feature

#2047 z-index eradication;
  lib/ui/elements/drawing.mjs
  lib/ui/elements/dropdown.mjs
  lib/ui/elements/pills.mjs
  public/css/_ui.css
  public/css/elements/_alert_confirm.css
  public/css/elements/_btnPanel.css
  public/css/elements/_dialog.css
  public/css/elements/_dropdown.css
  public/css/elements/_pills.css
  public/css/elements/_searchbox.css
  public/css/layout/_cloudinary.css
  public/css/layout/_divider.css
  public/css/layout/_image_preview.css
  public/css/layout/_infotip.css
  public/css/layout/_toolbars.css
  public/css/mapp.css
  public/css/ui.css
  public/views/_default.html
Labels: CSS

#2053 Do not debounce admin user requests
  mod/user/_user.js
Labels: Bug, Security

#2050 Xhr Utility: Onload and abort functionality
  lib/layer/format/mvt.mjs
  lib/ui/utils/idleLogout.mjs
  lib/utils/gazetteer.mjs
  lib/utils/xhr.mjs
Labels: Code, Documentation

#2058 Temporal Fix
  lib/utils/numericFormatter.mjs
  lib/utils/temporal.mjs
Labels: Bug

#2056 user select property for some elements;
  public/css/base/_button.css
  public/css/base/_common.css
  public/css/base/_globals.css
  public/css/elements/_alert_confirm.css
  public/css/elements/_chkbox.css
  public/css/elements/_dialog.css
  public/css/elements/_drawer.css
  public/css/elements/_pills.css
  public/css/layout/_cloudinary.css
  public/css/layout/_layerview.css
  public/css/layout/_legend.css
  public/css/layout/_map_attribution.css
  public/css/mapp.css
  public/css/ui.css
Labels: CSS

#2064 Fix saml import logic
  mod/user/saml.js
Labels: Bug

#2055 Dropdown filter search
  lib/dictionaries/de.mjs
  lib/dictionaries/en.mjs
  lib/dictionaries/es.mjs
  lib/dictionaries/fr.mjs
  lib/dictionaries/it.mjs
  lib/dictionaries/ja.mjs
  lib/dictionaries/pl.mjs
  lib/dictionaries/th.mjs
  lib/dictionaries/tr.mjs
  lib/dictionaries/zh.mjs
  lib/dictionaries/zh_trad.mjs
  lib/ui/elements/dropdown.mjs
  lib/ui/layers/filters.mjs
Labels: Documentation, UI

#2066 remove locale.layer merge from addlayer method
  lib/mapview/addLayer.mjs
Labels: Code

#2065 pill - inner close button always contrasting.
  public/css/base/_material_icons.css
  public/css/elements/_pills.css
  public/css/ui.css
Labels: CSS

#2069 Histogram template.
  mod/workspace/templates/_queries.js
  mod/workspace/templates/histogram.js
Labels: Feature

#2054 Ping Util
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/ping.mjs
  lib/utils/_utils.mjs
  lib/utils/ping.mjs
  mod/workspace/templates/_queries.js
  mod/workspace/templates/location_field_value.js
  tests/lib/ui/locations/entries/boolean.test.mjs
Labels: Feature

#2059 Remove vector_layer entry module
  lib/ui/locations/entries/_entries.mjs
  lib/ui/locations/entries/layer.mjs
  lib/ui/locations/entries/vector_layer.mjs
Labels: Feature, Code, Deprecated

#2079 Assign current geom in queryParams
  lib/utils/queryParams.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/paramString.test.mjs
  tests/lib/utils/queryParams.test.mjs
Labels: Bug

#2088 Correct merging of gazetteer with individual datasets
  lib/utils/gazetteer.mjs
Labels: Bug

#2077 Toast
  lib/ui/elements/_elements.mjs
  lib/ui/elements/toast.mjs
  public/css/_ui.css
  public/css/base/_button.css
  public/css/elements/_toast.css
  public/css/ui.css
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/toast.test.mjs
Labels: Feature, CSS, UI

#2094 Geom must allow a string property
  lib/utils/queryParams.mjs
  tests/lib/utils/queryParams.test.mjs
Labels: Bug

#2092 express v5 migration
  express.js
  package.json
Labels: Security

#2095 make btn-column scrollable
  public/css/layout/_toolbars.css
  public/css/ui.css
  public/views/_default.html
Labels: Bug, UI

#2096 Cookie module should return null without an ACL configured.
  mod/user/cookie.js
Labels: Bug

#2105 update docs for getBounds module method
  lib/mapview/getBounds.mjs
Labels: Documentation
