Repository GEOLYTIX/xyz, pull requests merged in 2025-02, with the labels that each got.

#1860 Store view params on mapview.locale.view
  lib/mapview/_mapview.mjs
Labels: Bug, Feature

#1866 Locale.View object: Fix crash when undefined/null
  lib/mapview/_mapview.mjs
Labels: Bug

#1867 The temporal utility mod must not throw an error to take down infoj p…
  lib/utils/temporal.mjs
Labels: Bug

#1870 Categorized Themes & Initial Filter Current
  lib/ui/layers/legends/categorized.mjs
Labels: Bug

#1872 Jenks must only parseFloat valid numbers
  lib/layer/featureFields.mjs
Labels: Bug

#1871 Avoid nullish assignment of entry.featureLookup on type layer
  lib/ui/locations/entries/layer.mjs
Labels: Bug

#1878 Dialog: Remove show function from modals
  lib/ui/elements/dialog.mjs
Labels: Bug

#1885 Return warning if drawing with no geom property
  lib/ui/layers/panels/draw.mjs
Labels: Bug

#1887 Improve parsing performance for keyvalue_dictionary execution.
  lib/plugins/keyvalue_dictionary.mjs
Labels: Code

#1857 jsoneditor element and userlayer plugin
  lib/plugins/_plugins.mjs
  lib/plugins/userLayer.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/jsoneditor.mjs
  lib/ui/locations/entries/json.mjs
  lib/ui/utils/jsonDataview.mjs
Labels: Feature, Plugin

#1868 Use workspace key as db for userlocale
  lib/plugins/userLocale.mjs
  lib/utils/userIndexedDB.mjs
  lib/utils/userLocale.mjs
  mod/workspace/_workspace.js
  mod/workspace/cache.js
  mod/workspace/getLocale.js
  public/views/_default.html
Labels: Feature

#1888 Core Templates should not be assigned to infoj fields
  mod/query.js
Labels: Bug

#1902 Mock documentation examples
  TESTING.md
Labels: Documentation

#1895 Check layer format in layer decorator
  lib/layer/decorate.mjs
  lib/mapview/addLayer.mjs
  lib/ui/locations/entries/layer.mjs
Labels: Bug

#1891 Template parameter check
  mod/workspace/getTemplate.js
Labels: Security

#1911 bump esbuild to v0.25
  package.json
Labels: Code, Security

#1909 Delete geometry should not finish an interaction, as no interaction h…
  lib/ui/locations/entries/geometry.mjs
Labels: Bug

#1906 Assign mapview.extent in viewExtent method
  lib/mapview/_mapview.mjs
Labels: Bug

#1910 disabled nested elements in view changeend method.
  lib/ui/layers/view.mjs
Labels: Bug

#1916 Return error message on view template request
  mod/utils/languageTemplates.js
  mod/view.js
Labels: Bug

#1944 KeyValue Dictionary Map and Key Value Dictionary from Layer
  lib/layer/_layer.mjs
  lib/plugins/keyvalue_dictionary.mjs
Labels: Bug
