Repository GEOLYTIX/xyz, pull requests merged in 2025-01, with the labels that each got.

#1779 Graduated theme parser
  lib/layer/styleParser.mjs
  tests/assets/styles/styleParser.json
  tests/lib/layer/_layer.test.mjs
  tests/lib/layer/styleParser.test.mjs
Labels: Bug, Code, Documentation

#1785 Bump OL to 10.3.1 to include clear cache fix.
  lib/layer/format/mvt.mjs
  lib/mapp.mjs
  lib/utils/olScript.mjs
  public/views/_default.html
  public/views/_test.html
  tests/lib/layer/format/mvt.test.mjs
Labels: Bug, Code, Testing

#1788 Entry layer tweak
  lib/ui/locations/entries/layer.mjs
Labels: Bug

#1783 Reduce mapview complexity
  lib/mapview/_mapview.mjs
Labels: Code, Documentation

#1786 Entry Dataviews Refresh
  lib/ui/Dataview.mjs
  lib/ui/Tabview.mjs
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/locations/entries/dataview.mjs
  lib/ui/locations/listview.mjs
  lib/ui/utils/jsonDataview.mjs
Labels: Bug

#1758 Userlocal jsonparser
  api/api.js
  lib/layer/format/maplibre.mjs
  lib/layer/styleParser.mjs
  lib/plugins/_plugins.mjs
  lib/plugins/userIDB.mjs
  lib/plugins/userLocale.mjs
  lib/plugins/zoomBtn.mjs
  lib/ui/layers/listview.mjs
  lib/ui/layers/panels/dataviews.mjs
  lib/utils/_utils.mjs
  lib/utils/jsonParser.mjs
  lib/utils/userIndexedDB.mjs
  lib/utils/userLocale.mjs
  mod/workspace/cache.js
  mod/workspace/getLocale.js
  public/views/_default.html
  tests/assets/userLocale/jsonParser.json
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/jsonParser.test.mjs
  tests/workspace.json
Labels: Feature, Testing, Plugin

#1801 Provide user roles param for admin requests.
  mod/user/auth.js
Labels: Feature, Testing

#1793 Allow for layer entry without query [featureSet / featureLookup] configuration
  lib/location/get.mjs
  lib/mapview/interactions/highlight.mjs
  lib/ui/locations/entries/layer.mjs
Labels: Feature

#1806 Fix SAML Logout Redirect Issue 🩹
  api/api.js
  mod/user/saml.js
Labels: Bug

#1642 CSV Upload Utility
  lib/dictionaries/en.mjs
  lib/ui/utils/jsonDataview.mjs
  lib/utils/_utils.mjs
  lib/utils/csvUpload.mjs
Labels: Feature

#1809 css structure (sync with minor)
  public/css/_button.css
  public/css/_colours.css
  public/css/_dialog.css
  public/css/_icons.css
  public/css/_inputs.css
  public/css/_mapp.css
  public/css/_tabulator.scss
  public/css/_ui.css
  public/css/base/_button.css
  public/css/base/_colours.css
  public/css/base/_common.css
  public/css/base/_font.css
  public/css/base/_globals.css
  public/css/base/_icons.css
  public/css/base/_inputs.css
  public/css/elements/_alert_confirm.css
  public/css/elements/_btnPanel.css
  public/css/elements/_chkbox.css
  public/css/elements/_dialog.css
  public/css/elements/_drawer.css
  public/css/elements/_dropdown.css
  public/css/elements/_pills.css
  public/css/elements/_searchbox.css
  public/css/elements/_slider.css
  public/css/layout/_infotip.css
  public/css/layout/_layerview.css
  public/css/layout/_legend.css
  public/css/layout/_locationview.css
  public/css/layout/_map_attribution.css
  public/css/layout/_ol.css
  public/css/layout/_popup.css
  public/css/layout/_tabview.css
  public/css/layout/_toolbars.css
  public/css/mapp.css
  public/css/ui.css
Labels: Code, CSS

#1819 Security Enhancements and Rate Limiting 🔐
  express.js
  jsdoc_xyz.json
  package.json
Labels: Security

#1818 A numeric value only may not be returned from the query module.
  mod/query.js
Labels: Bug

#1829 Fix jsdocs return statement for csvUpload
  lib/utils/csvUpload.mjs
Labels: Documentation

#1815 processEnv utility module (sync with minor)
  api/api.js
  express.js
  mod/provider/cloudfront.js
  mod/provider/file.js
  mod/sign/cloudfront.js
  mod/sign/cloudinary.js
  mod/sign/s3.js
  mod/user/acl.js
  mod/user/auth.js
  mod/user/cookie.js
  mod/user/delete.js
  mod/user/fromACL.js
  mod/user/key.js
  mod/user/list.js
  mod/user/login.js
  mod/user/register.js
  mod/user/saml.js
  mod/user/token.js
  mod/user/verify.js
  mod/utils/dbs.js
  mod/utils/envReplace.js
  mod/utils/logger.js
  mod/utils/mailer.js
  mod/utils/processEnv.js
  mod/utils/reqHost.js
  mod/view.js
  mod/workspace/cache.js
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
  mod/workspace/getTemplate.js
  mod/workspace/mergeTemplates.js
  mod/workspace/templates/_msgs.js
Labels: Code

#1820 It should be possible to toggle graduated theme categories on the label.
  lib/layer/themes/graduated.mjs
  lib/ui/elements/_elements.mjs
  lib/ui/elements/themeLegendSwitch.mjs
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/graduated.mjs
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/themeLegendSwitch.test.mjs
Labels: Feature

#1824 Automatic Code Formatting husky/lint-stage/prettier 🐶🧹💅
  .husky/pre-commit
  package.json
  tests/mod/query.test.mjs
  tests/workspace.json
Labels: Documentation

#1826 Link Button: allow locale to be passed as flag
  lib/plugins/link_button.mjs
  tests/browser/local.test.mjs
  tests/plugins/link_button.test.mjs
Labels: Feature, Plugin

#1781 Layer dataviews target
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/layers/view.mjs
  lib/ui/locations/entries/dataview.mjs
  public/css/elements/_drawer.css
  public/css/ui.css
  tests/assets/dataviews/dataviews_panel.json
  tests/lib/ui/layers/_layers.test.mjs
  tests/lib/ui/layers/panels/dataviews.test.mjs
  tests/lib/ui/locations/entries/dataview.test.mjs
Labels: Feature

#1803 layer_template query param
  mod/query.js
Labels: Feature, Code, Security

#1839 Filter Visual Changes
  lib/ui/layers/filters.mjs
  lib/ui/layers/view.mjs
  public/css/base/_icons.css
  public/css/ui.css
  public/icons/icon-filter.svg
  public/icons/icon-zoom-in.svg
Labels: UI

#1842 Login rate limit
  mod/user/_user.js
  mod/user/fromACL.js
  mod/user/register.js
Labels: Security
