Repository GEOLYTIX/xyz, pull requests merged in 2025-05, with the labels that each got.

#2026 Nested locales
  mod/utils/envReplace.js
  mod/workspace/_workspace.js
  mod/workspace/getLayer.js
  mod/workspace/getLocale.js
  mod/workspace/getTemplate.js
  mod/workspace/mergeTemplates.js
  public/views/_default.html
  tests/assets/workspace_nested_locales.json
  tests/mod/workspace/_workspace.test.mjs
  tests/mod/workspace/getTemplate.test.mjs
Labels: Feature, Code

#2117 Return dropdown node without pills container.
  lib/ui/elements/dropdown.mjs
  public/views/_default.html
  tests/lib/ui/elements/_elements.test.mjs
  tests/lib/ui/elements/dropdown.test.mjs
Labels: Bug

#2122 Ensure layer always has layer.params.fields
  lib/layer/format/vector.mjs
Labels: Bug

#2120 Allow configuration to filter the available options for circle drawing
  lib/ui/elements/drawing.mjs
Labels: Feature

#2112 userIDB plugin
  lib/plugins/_plugins.mjs
  lib/plugins/userIDB.mjs
  lib/utils/userIndexedDB.mjs
  lib/utils/userLocale.mjs
  public/views/_default.html
Labels: Feature, Plugin

#2126 Import maplibre from esmImport util
  lib/layer/format/maplibre.mjs
Labels: Code

#2127 Bump jsoneditor import from esmImport util
  lib/ui/elements/jsoneditor.mjs
Labels: Code

#2129 Add mapboxStyle layer format
  lib/layer/format/_format.mjs
  lib/layer/format/mapboxStyle.mjs
Labels: Feature

#2136 fix(theme): Categorized Theme missing nowrap property
  lib/ui/layers/legends/categorized.mjs
  lib/ui/layers/legends/graduated.mjs
Labels: Bug

#2141 fix(entries.layer): Assignment of layer clone to entry object
  lib/ui/locations/entries/layer.mjs
  lib/ui/locations/entries/vector_layer.mjs
  tests/lib/ui/locations/entries/_entries.test.mjs
  tests/lib/ui/locations/entries/boolean.test.mjs
  tests/lib/ui/locations/entries/layer.test.mjs
Labels: Bug

#2142 fix(dataview): Disable entry checkbox on null when queryCheck is used
  lib/ui/locations/entries/dataview.mjs
Labels: Bug

#2148 fix(maplibre): include compiled mapbox-gl-rtl-text.js
  .gitignore
  lib/layer/format/maplibre.mjs
  public/js/mapbox-gl-rtl-text.js
Labels: Bug

#2139 feat(mapview): set zIndex in addLayer as mapview property
  lib/mapview/addLayer.mjs
Labels: Feature

#2130 feat(dataview): target dataview/s in dialogs
  lib/ui/layers/panels/dataviews.mjs
  lib/ui/locations/entries/dataview.mjs
  lib/ui/utils/_utils.mjs
  lib/ui/utils/dataviewDialog.mjs
Labels: Feature, Documentation, CSS, UI

#2157 Check userLocale in default script
  lib/utils/userLocale.mjs
  public/views/_default.html
Labels: Feature

#2151 Assign mapButton to mapview object
  lib/plugins/admin.mjs
  lib/plugins/dark_mode.mjs
  lib/plugins/feature_info.mjs
  lib/plugins/fullscreen.mjs
  lib/plugins/link_button.mjs
  lib/plugins/locator.mjs
  lib/plugins/login.mjs
  lib/plugins/userIDB.mjs
  lib/plugins/zoomBtn.mjs
  lib/plugins/zoomToArea.mjs
  public/views/_default.html
  tests/plugins/link_button.test.mjs
Labels: Code

#2150 Assign preserveDrawingBuffer as contextAttribute
  lib/layer/format/maplibre.mjs
Labels: Bug, Code

#2165 fix(dialog): Prevent left and top from going negative
  lib/ui/elements/dialog.mjs
  lib/ui/utils/dataviewDialog.mjs
Labels: Bug

#2167 (bug): Apply zIndex to mapbox style layer
  lib/layer/format/mapboxStyle.mjs
Labels: Bug

#2171 (bug) : Locale.layer must not be deleted
  mod/workspace/getLocale.js
Labels: Bug

#2168 (bug): Encode userLocale Naming
  lib/ui/elements/userLocale.mjs
Labels: Bug

#2182 (bug): Dropdown Fixes
  lib/ui/elements/dropdown.mjs
Labels: Bug

#2180 (bug): Non cached file templates should not be merged on each fetch
  mod/workspace/getTemplate.js
Labels: Bug
