Repository GEOLYTIX/xyz, pull requests merged in 2025-07, with the labels that each got.

#2237 bug(dialog): Fix alignment of buttons
  lib/ui/elements/dialog.mjs
  tests/lib/ui/elements/dialog.test.mjs
Labels: Bug

#2243 Review node mailer conditions, defaults and warnings.
  mod/utils/mailer.js
  mod/utils/processEnv.js
  tests/mod/user/register.test.mjs
Labels: Code

#2246 The selected titles should not be assigned with the keepPlaceholder option
  lib/ui/elements/dropdown.mjs
Labels: Bug

#2260 fix(gazetteer): Use object assign to prevent duplicated search results
  lib/utils/gazetteer.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/gazetteer.test.mjs
Labels: Bug, Testing

#2228 feature(layer): JSON Editor layer panel and element
  lib/layer/decorate.mjs
  lib/mapview/removeLayer.mjs
  lib/plugins/userLayer.mjs
  lib/ui/elements/jsoneditor.mjs
  lib/ui/layers/_layers.mjs
  lib/ui/layers/panels/jsonEditor.mjs
  lib/ui/utils/_utils.mjs
  lib/ui/utils/layerJSE.mjs
  public/css/_ui.css
  public/css/elements/_jse.css
  public/css/ui.css
Labels: Feature, Code

#2264 fix(styleParser): Theme parsing issue
  lib/layer/decorate.mjs
  lib/layer/styleParser.mjs
Labels: Bug

#2235 feature(flyTo): Fly to the extent of mvt entry type layers with featureSet/Lookup
  lib/layer/decorate.mjs
  lib/location/decorate.mjs
  lib/ui/locations/entries/geometry.mjs
  lib/ui/locations/entries/layer.mjs
  lib/ui/locations/entries/pin.mjs
  lib/utils/_utils.mjs
  lib/utils/gazetteer.mjs
  mod/workspace/templates/_queries.js
  mod/workspace/templates/feature_extent.js
  mod/workspace/templates/layer_extent.js
  tests/lib/ui/locations/entries/geometry.test.mjs
  tests/lib/ui/locations/entries/pin.test.mjs
  tests/lib/utils/_utils.test.mjs
  tests/lib/utils/createExtent.test.mjs
  tests/mod/workspace/templates/_templates.test.mjs
  tests/mod/workspace/templates/layer_extent.test.mjs
Labels: Feature, Documentation

#2273 Provide svg fallback for icon.url
  lib/utils/olStyle.mjs
Labels: Bug

#2281 feat(legends.categorized): Distribution Count - Format Number
  lib/ui/layers/legends/categorized.mjs
Labels: Feature

#2290 fix(mvt): WKT Properties not allowing callback
  lib/layer/format/mvt.mjs
Labels: Bug

#2293 feat(style): Allow Line Dash Property
  lib/utils/olStyle.mjs
Labels: Feature

#2296 fix(location.updateCount): Move updateCount to filter panel
  lib/ui/layers/filters.mjs
  lib/ui/layers/panels/filter.mjs
Labels: Bug, Code

#2297 CSS - common - outlined class.
  lib/ui/locations/entries/link.mjs
  public/css/base/_common.css
  public/css/ui.css
Labels: Code, Documentation, CSS
